"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useLanguage } from "@/lib/language-provider";
import type { DriverProfile } from "@/lib/driver-operations";
const copy = {
  en: { title: "Driver profile", official: "Official driver name", name: "Display name", phone: "Phone", email: "Account email", driver: "Driver ID", vehicle: "Default vehicle", language: "Language", save: "Save profile", photo: "Change photo", photoHelp: "JPEG, PNG or WebP · up to 5 MB", locked: "Official identity is managed by the office. Display name changes do not alter bookings.", password: "Change password", current: "Current password", new: "New password", confirm: "Confirm password", passwordHelp: "Use at least 12 characters. Reauthenticate your own account. Other portal sessions will be signed out.", saved: "Saved successfully", error: "Unable to complete this request. Please retry or contact operations.", loading: "Loading…", retry: "Retry", mismatch: "Passwords must match and contain at least 12 characters.", working: "Saving…" },
  th: { title: "โปรไฟล์คนขับ", official: "ชื่อคนขับอย่างเป็นทางการ", name: "ชื่อที่แสดง", phone: "โทรศัพท์", email: "อีเมลบัญชี", driver: "รหัสคนขับ", vehicle: "รถประจำ", language: "ภาษา", save: "บันทึกโปรไฟล์", photo: "เปลี่ยนรูป", photoHelp: "JPEG, PNG หรือ WebP · ไม่เกิน 5 MB", locked: "สำนักงานดูแลชื่ออย่างเป็นทางการ การเปลี่ยนชื่อที่แสดงไม่แก้ไขข้อมูลการจอง", password: "เปลี่ยนรหัสผ่าน", current: "รหัสผ่านปัจจุบัน", new: "รหัสผ่านใหม่", confirm: "ยืนยันรหัสผ่าน", passwordHelp: "อย่างน้อย 12 ตัวอักษร ต้องยืนยันบัญชีของคุณ ระบบจะออกจากระบบบนอุปกรณ์อื่น", saved: "บันทึกสำเร็จ", error: "ดำเนินการไม่สำเร็จ กรุณาลองอีกครั้งหรือติดต่อฝ่ายปฏิบัติการ", loading: "กำลังโหลด…", retry: "ลองอีกครั้ง", mismatch: "รหัสผ่านต้องตรงกันและมีอย่างน้อย 12 ตัวอักษร", working: "กำลังบันทึก…" }
};
export function DriverProfilePage() {
  const router = useRouter();
  const { language, setLanguage } = useLanguage(); const l = copy[language];
  const [profile, setProfile] = useState<DriverProfile | null>(null); const [name, setName] = useState(""); const [phone, setPhone] = useState("");
  const [error, setError] = useState(false); const [message, setMessage] = useState(false); const [busy, setBusy] = useState(false);
  const [uploading, setUploading] = useState(false);
  const applyProfile = useCallback((p: DriverProfile) => { setProfile(p); setName(p.displayName); setPhone(p.phone); window.dispatchEvent(new CustomEvent("ees-driver-profile-updated", { detail: p })); }, []);
  const load = useCallback(async () => { try { const r = await fetch("/api/driver/profile", { cache: "no-store" }); if (!r.ok) throw new Error(); const p = await r.json() as DriverProfile; applyProfile(p); setError(false); return true; } catch { setError(true); return false; } }, [applyProfile]);
  useEffect(() => { void load(); }, [load]);
  async function request(url: string, init: RequestInit) { setBusy(true); setError(false); setMessage(false); try { const r = await fetch(url, init); if (!r.ok) throw new Error(); if (url.endsWith("/avatar")) applyProfile(await r.json() as DriverProfile); else if (!await load()) throw new Error(); setMessage(true); router.refresh(); } catch { setError(true); } finally { setBusy(false); setUploading(false); } }
  async function password(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    const body = { currentPassword: String(data.get("currentPassword")), password: String(data.get("password")), confirmPassword: String(data.get("confirmPassword")) };
    if (body.password !== body.confirmPassword || body.password.length < 12) { setError(true); return; }
    await request("/api/driver/profile/password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); form.reset();
  }
  const field = "mt-1 min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-base";
  return <main className="mx-auto max-w-3xl space-y-4 px-4 py-5"><h1 className="text-2xl font-black">{l.title}</h1>{error ? <div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{l.error}<button onClick={() => void load()} className="ml-3 underline">{l.retry}</button></div> : null}{message ? <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{l.saved}</p> : null}{!profile ? <p>{l.loading}</p> : <>
    <section className="overflow-hidden rounded-2xl border border-brand-100 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xs font-black uppercase tracking-widest text-brand-700">{language === "th" ? "โปรไฟล์" : "Profile"}</h2><div className="flex items-center gap-4">{profile.avatarUrl ? <Image key={profile.avatarUrl} unoptimized src={profile.avatarUrl} width={80} height={80} alt={profile.displayName} className="h-20 w-20 shrink-0 rounded-2xl object-cover ring-4 ring-brand-50" /> : <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-2xl bg-brand-50 text-3xl font-bold text-brand-700">{profile.displayName.slice(0, 1)}</div>}<div className="min-w-0"><p className="mb-2 break-words text-lg font-black text-slate-950">{profile.displayName}</p><label className="inline-flex min-h-11 cursor-pointer items-center rounded-xl border border-brand-200 px-3 text-sm font-bold text-brand-800 hover:bg-brand-50">{uploading ? language === "th" ? "กำลังอัปโหลด…" : "Uploading…" : l.photo}<input aria-label={l.photo} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.size || file.size > 5242880 || !["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setError(true); setMessage(false); return; } const body = new FormData(); body.append("avatar", file); setUploading(true); void request("/api/driver/profile/avatar", { method: "POST", body }); }} /></label><p className="mt-1 text-xs text-slate-500">{l.photoHelp}</p></div></div>
      <dl className="mt-4 divide-y text-sm">{[[l.official, profile.officialName], [l.email, profile.email], [l.driver, profile.driverId], [l.vehicle, profile.vehicle || "—"]].map(([label, value]) => <div className="flex justify-between gap-3 py-2" key={label}><dt className="text-slate-500">{label}</dt><dd className="max-w-[65%] break-all text-right font-semibold">{value}</dd></div>)}</dl><p className="mt-2 text-xs leading-5 text-slate-500">{l.locked}</p></section>
    <form className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" onSubmit={(e) => { e.preventDefault(); void request("/api/driver/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: name, phone }) }); }}><h2 className="text-xs font-black uppercase tracking-widest text-brand-700">{language === "th" ? "ข้อมูลส่วนตัว" : "Personal details"}</h2><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">{l.name}<input className={field} value={name} maxLength={100} required disabled={busy} onChange={(e) => setName(e.target.value)} /></label><label className="block text-sm font-semibold">{l.phone}<input type="tel" className={field} value={phone} maxLength={30} disabled={busy} onChange={(e) => setPhone(e.target.value)} /></label></div><button className="btn-primary w-full min-h-12 sm:w-auto" disabled={busy}>{busy ? l.working : l.save}</button></form>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-xs font-black uppercase tracking-widest text-brand-700">{language === "th" ? "การตั้งค่า" : "Preferences"}</h2><label className="text-sm font-bold">{l.language}<select className={field} value={language} onChange={(e) => setLanguage(e.target.value as "en" | "th")}><option value="en">English</option><option value="th">ไทย</option></select></label></section>
    <form className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4" onSubmit={(e) => void password(e)}><h2 className="font-bold">{l.password}</h2><p className="break-all text-sm text-slate-500">{profile.email}</p><p className="text-xs leading-5 text-slate-500">{l.passwordHelp}</p>{[["currentPassword", l.current, "current-password"], ["password", l.new, "new-password"], ["confirmPassword", l.confirm, "new-password"]].map(([key, label, autocomplete]) => <label key={key} className="block text-sm font-semibold">{label}<input name={key} type="password" autoComplete={autocomplete} minLength={key === "currentPassword" ? 1 : 12} maxLength={128} required disabled={busy} className={field} /></label>)}<button className="btn-secondary w-full min-h-12" disabled={busy}>{busy ? l.working : l.password}</button></form>
  </>}</main>;
}
