const fs=require('node:fs'), path=require('node:path'), test=require('node:test'), assert=require('node:assert/strict'), ts=require('typescript');
const root=path.join(__dirname,'..');
function load(file,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(k=>k in deps?deps[k]:require(k),m,m.exports);return m.exports;}
const ops=load('lib/driver-operations.ts');
class DriverPortalError extends Error{constructor(status,message){super(message);this.status=status}}
const ids=['00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000003'];
function database(){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());const yesterday=ops.shiftBangkokDate(today,-1);
 const bookings=ids.map((id,i)=>({id,driver_id:'26',booking_date:i===2?yesterday:today,pickup_time:i===0?'09:00':null,pickup:'QMB',dropoff:'BKK',vehicle_registration:i===1?null:'1998',vehicle:'FOUR_WHEEL_TRUCK',status:null,client:{name:'Customer'},job_order_number:'EES-'+i}));
 const events=[]; const calls=[];
 const tables={booking_diary:bookings,driver_job_events:events,drivers:[{id:'26',name:'Renamed driver',vehicle_reg:'9999',vehicle_type:'FOUR_WHEEL_TRUCK',active:true},{id:'27',name:'Other driver',vehicle_reg:'8888',active:true}],driver_accounts:[{driver_id:'26',active:true}]};
 function make(table){const filters=[],orders=[];let fields='',options={},offset=0,end=Infinity,single=false;const q={
  select(value,opts={}){fields=value;options=opts;calls.push([table,'select',value,opts]);return q},
  eq(k,v){calls.push([table,'eq',k,v]);filters.push(['eq',k,v]);return q},lt(k,v){calls.push([table,'lt',k,v]);filters.push(['lt',k,v]);return q},gte(k,v){calls.push([table,'gte',k,v]);filters.push(['gte',k,v]);return q},in(k,v){calls.push([table,'in',k,v]);filters.push(['in',k,v]);return q},not(k,op,v){filters.push(['not',k,v]);return q},is(k,v){filters.push(['is',k,v]);return q},ilike(k,v){filters.push(['ilike',k,v]);return q},or(v,o){calls.push([table,'or',v,o]);return q},order(k,o={}){orders.push([k,o]);return q},range(a,b){offset=a;end=b;return Promise.resolve(result())},maybeSingle(){single=true;return Promise.resolve(result())},then(resolve,reject){return Promise.resolve(result()).then(resolve,reject)}
 };
 function result(){if(!tables[table])throw Error('Unexpected table '+table);let rows=tables[table].filter(row=>filters.every(([op,k,v])=>{
   if(k.startsWith('started.'))return events.some(e=>e.booking_id===row.id&&(k.endsWith('event_type')?e.event_type===v:String(e.driver_id)===String(v)));
   if(k==='finished')return !events.some(e=>e.booking_id===row.id&&e.event_type==='job_completed');
   if(k==='finished.event_type')return true;
   if(k.startsWith('driver_match')||k.startsWith('job_match'))return true;
   const value=k==='event_time'?Date.parse(row[k]):row[k],target=k==='event_time'?Date.parse(v):v;
   return op==='eq'?String(value)===String(target):op==='in'?v.map(String).includes(String(value)):op==='lt'?value<target:op==='gte'?value>=target:op==='not'?value!=null:op==='is'?value==null:op==='ilike'?String(value).toLowerCase().includes(String(v).replaceAll('%','').toLowerCase()):true;
 }));
 for(const [key,opts]of orders.reverse())rows=rows.sort((a,b)=>String(a[key]??'99').localeCompare(String(b[key]??'99'))*(opts.ascending===false?-1:1));
 const count=rows.length;rows=rows.slice(offset,end+1).map(row=>fields.includes('booking:booking_diary')?{...row,booking:bookings.find(b=>b.id===row.booking_id)}:row);
 return{data:options.head?null:single?rows[0]||null:rows,count:options.count==='exact'?count:null,error:null};
 }
 return q;}
 const admin={from:make}; const session={driverId:'26',driverName:'Renamed driver',vehicleRegistration:'9999',vehicleType:'FOUR_WHEEL_TRUCK'};
 const deps={'server-only':{},'@/lib/admin-user-management-server':{createServerSupabaseAdmin:()=>admin},'@/lib/driver-portal-server':{DriverPortalError,DRIVER_JOB_SELECT:'id,driver_id,booking_date,vehicle_registration',bangkokDateKey:date=>ops.bangkokOperationalDate(date||new Date()),toDriverJob:(row,identity)=>({id:row.id,driverId:String(row.driver_id),bookingDate:row.booking_date,pickupTime:row.pickup_time,clientName:row.client?.name,pickupName:row.pickup,dropoffName:row.dropoff,vehicleRegistration:row.vehicle_registration||identity.vehicleRegistration,vehicleType:row.vehicle||identity.vehicleType,bookingStatus:row.status})},'@/lib/driver-profile-server':{readDriverProfile(){throw Error('No per-row profile lookup')}},'@/lib/driver-operations':ops};
 const work=load('lib/driver-work-server.ts',deps);
 function complete(index,date=today){for(const [i,event_type]of ['pickup_arrived','pickup_departed','delivery_arrived','job_completed'].entries())events.push({id:String(events.length),booking_id:ids[index],driver_id:'26',event_type,event_time:date+`T10:0${i}:00+07:00`,latitude:13,longitude:100})}
 return{today,yesterday,bookings,events,calls,admin,work,session,complete,deps};
}
test('Office History includes today and reconciles every job through two completions',async()=>{const db=database();db.complete(0);let portal=await db.work.driverHistoryWork(db.session),office=await db.work.operationsHistory(db.admin,new URLSearchParams({driver_id:'26'}));assert.equal(office.total,1);assert.deepEqual(office.rows.map(r=>r.job.id),portal.rows.map(r=>r.job.id));db.complete(1);portal=await db.work.driverHistoryWork(db.session);office=await db.work.operationsHistory(db.admin,new URLSearchParams({driver_id:'26'}));assert.equal(office.total,2);assert.deepEqual(office.rows.map(r=>r.job.id),portal.rows.map(r=>r.job.id));assert.equal(office.pageSize,25);assert.ok(!db.calls.some(c=>c[0]==='driver_job_events'&&c[1]==='lt'&&c[2]==='event_time'));});
test('historical ownership and vehicle snapshots survive reassignment and current vehicle changes',async()=>{const db=database();db.complete(0);db.complete(1);db.bookings[0].driver_id='27';const portal=await db.work.driverHistoryWork(db.session);const office=await db.work.operationsHistory(db.admin,new URLSearchParams({driver_id:'26'}));assert.equal(portal.rows.length,2);assert.equal(office.total,2);const prior=office.rows.find(row=>row.job.id===ids[0]);assert.equal(prior.driverId,'26');assert.equal(prior.driverName,'Renamed driver');assert.equal(prior.job.vehicleRegistration,'1998');assert.equal(office.rows.find(row=>row.job.id===ids[1]).job.vehicleRegistration,null);assert.ok(!db.calls.some(c=>c[0]==='booking_diary'&&c[1]==='eq'&&c[2]==='driver_id'&&c[3]==='26'));});
test('Office KPIs count scheduled work separately from jobs completed today',async()=>{const db=database();db.complete(2);let result=await db.work.driverOperations(db.admin);assert.equal(result.summary.jobsToday,2);assert.equal(result.summary.driversToday,1);assert.equal(result.summary.activeNow,0);assert.equal(result.summary.completedToday,1);db.events.push({id:'new',booking_id:ids[0],driver_id:'26',event_type:'pickup_arrived',event_time:db.today+'T12:00:00+07:00',latitude:null,longitude:null});result=await db.work.driverOperations(db.admin);assert.equal(result.summary.activeNow,1);assert.equal(result.summary.completedToday,1);assert.equal(result.driverActivity['26'].jobsToday,2);});
test('query failures and unavailable counts throw instead of returning zero operations',async()=>{const db=database();const q={select(){return q},eq(){return q},not(){return q},order(){return q},range:async()=>({data:null,error:{code:'failure'}})};await assert.rejects(db.work.driverOperations({from:()=>q}),{status:503});const history={select(){return history},eq(){return history},order(){return history},range:async()=>({data:[],count:null,error:null})};await assert.rejects(db.work.operationsHistory({from:()=>history},new URLSearchParams()),{status:503});});
test('25-row pagination keeps all completed rows and exposes a true total',async()=>{const db=database();db.bookings.splice(0,db.bookings.length,...Array.from({length:31},(_,i)=>({...db.bookings[0],id:'row-'+i,driver_id:'26'})));db.events.splice(0,db.events.length,...db.bookings.map((b,i)=>({id:String(i).padStart(2,'0'),booking_id:b.id,driver_id:'26',event_type:'job_completed',event_time:db.today+'T10:00:00+07:00'})));const a=await db.work.operationsHistory(db.admin,new URLSearchParams()),b=await db.work.operationsHistory(db.admin,new URLSearchParams('page=1'));assert.equal(a.total,31);assert.equal(a.rows.length,25);assert.equal(b.rows.length,6);assert.equal(a.hasMore,true);assert.equal(b.hasMore,false);assert.equal(new Set([...a.rows,...b.rows].map(r=>r.job.id)).size,31);});
test('Bangkok completion-day edges, inclusive To dates and database search remain explicit',async()=>{assert.equal(ops.bangkokOperationalDate('2026-10-05T17:00:00Z'),'2026-10-06');assert.equal(ops.bangkokOperationalDate('2026-10-06T16:59:59Z'),'2026-10-06');assert.equal(ops.bangkokOperationalDate('2026-10-06T17:00:00Z'),'2026-10-07');const db=database();await db.work.operationsHistory(db.admin,new URLSearchParams({from:'2026-10-06',to:'2026-10-06',q:'Renamed driver'}));assert.ok(db.calls.some(c=>c[1]==='lt'&&c[2]==='event_time'&&c[3]==='2026-10-07T00:00:00+07:00'));assert.ok(db.calls.some(c=>c[1]==='or'&&c[2].includes('job_order_number')));await assert.rejects(db.work.operationsHistory(db.admin,new URLSearchParams('from=2026-02-31')),{status:400});});
test('new driver-statistics endpoint enforces administrator access before reading a client driver ID',async()=>{class AdminApiError extends Error{constructor(status){super('Denied');this.status=status}}let called=false;const route=load('app/api/admin/driver-operations/drivers/[driverId]/route.ts',{'@/lib/admin-user-management-server':{AdminApiError,requireAdminAccess:async()=>{throw new AdminApiError(403)}},'@/lib/driver-portal-server':{DriverPortalError},'@/lib/driver-work-server':{operationsDriverDetail:()=>{called=true}}});const response=await route.GET(new Request('https://app.test/api'),{params:Promise.resolve({driverId:'26'})});assert.equal(response.status,403);assert.equal(called,false);assert.equal(response.headers.get('cache-control'),'private, no-store');});
test('a completion permits historical read access only; it never authorizes another driver write',async()=>{const db=database();db.complete(0);db.bookings[0].driver_id='27';const portal=load('lib/driver-portal-server.ts',{'server-only':{},'node:crypto':require('node:crypto'),'next/headers':{},'@supabase/supabase-js':{},react:{cache:f=>f},'@/lib/admin-user-management-server':{createServerSupabaseAdmin:()=>db.admin}});const visible=await portal.getDriverVisibleJob(db.session,ids[0]);assert.ok(visible);assert.equal(await portal.getAssignedDriverJob(db.session,ids[0]),null);assert.equal(await portal.getDriverVisibleJob({...db.session,driverId:'99'},ids[0]),null);const writes=load('lib/driver-job-events-server.ts',{'server-only':{},'@/lib/admin-user-management-server':{createServerSupabaseAdmin:()=>db.admin},'@/lib/driver-portal-server':portal,'@/lib/driver-portal':load('lib/driver-portal.ts')});await assert.rejects(writes.appendDriverJobEvent(db.session,ids[0],{eventType:'job_completed'}),{status:404});});
test('a completed reassigned job cannot re-enter the new assignee’s Home counts',async()=>{const db=database();db.complete(0);db.bookings[0].driver_id='27';const portalDeps=db.deps['@/lib/driver-portal-server'];portalDeps.listAssignedDriverJobs=async session=>db.bookings.filter(row=>row.driver_id===session.driverId).map(row=>portalDeps.toDriverJob(row,session));const work=await db.work.driverHomeWork({...db.session,driverId:'27'});const normalized=ops.driverHomeJobs(work.map(row=>row.job),Object.fromEntries(work.map(row=>[row.job.id,row.events])),db.today,'27');assert.equal(work[0].events.length,4);assert.equal(normalized.remainingTodayCount,0);assert.equal(normalized.nextJob,null)});
test('page-show refresh can supersede the initial progress read without leaving completion stuck loading',async()=>{
 const React=require('react'),runtime=require('react/jsx-runtime');const saved=["pickup_arrived","pickup_departed","delivery_arrived","job_completed"].map((eventType,i)=>({id:String(i),eventType,eventTime:'2026-10-06T07:56:00Z',latitude:13,longitude:100}));
 const states=[],refs=[],effects=[],handlers={},pending=[];let stateIndex=0,refIndex=0;
 const hooks={...React,useState(initial){const index=stateIndex++;if(!(index in states))states[index]=initial;return[states[index],value=>{states[index]=typeof value==='function'?value(states[index]):value}]},useRef(initial){const index=refIndex++;return refs[index]||(refs[index]={current:initial})},useCallback:fn=>fn,useEffect(fn){effects.push(fn)}};
 const oldFetch=global.fetch,oldWindow=global.window,oldDocument=global.document;
 global.fetch=()=>new Promise(resolve=>pending.push(resolve));global.window={addEventListener:(key,fn)=>handlers[key]=fn,removeEventListener(){},setTimeout,clearTimeout};global.document={visibilityState:'visible',addEventListener(){},removeEventListener(){}};
 const dependencies={'@/lib/driver-operations':ops,'next/navigation':{useRouter:()=>({refresh(){}})},react:hooks,'react/jsx-runtime':runtime,'@/lib/language-provider':{useLanguage:()=>({language:'en'})},'@/lib/driver-portal':load('lib/driver-portal.ts'),'@/lib/driver-vehicle-types':load('lib/driver-vehicle-types.ts')};
 const module={exports:{}};function component(file){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(key=>key==='./driver-route-options'?component('components/driver/driver-route-options.tsx'):key==='./driver-disclosure'?component('components/driver/driver-disclosure.tsx'):key in dependencies?dependencies[key]:require(key),m,m.exports);return m.exports}
 try{const {DriverJobDetail}=component('components/driver/driver-job-detail.tsx');DriverJobDetail({job:{id:ids[0],bookingDate:'2026-10-06',pickupName:'P',dropoffName:'D'},depot:{name:'EES Depot'}});effects[0]();handlers.pageshow();assert.equal(pending.length,2);pending[1]({ok:true,json:async()=>({events:saved})});await new Promise(setImmediate);assert.equal(states[1],false);assert.equal(states[0].length,4);pending[0]({ok:true,json:async()=>({events:[]})});await new Promise(setImmediate);assert.equal(states[0].length,4);assert.equal(states[1],false)}finally{global.fetch=oldFetch;global.window=oldWindow;global.document=oldDocument}
});
test('a past-day active handoff remains the current job for its new assignee',async()=>{const db=database();db.bookings[0].booking_date=db.yesterday;db.bookings[0].driver_id='27';db.events.push({id:'arrived',booking_id:ids[0],driver_id:'26',event_type:'pickup_arrived',event_time:db.yesterday+'T10:00:00+07:00'});const portalDeps=db.deps['@/lib/driver-portal-server'];portalDeps.listAssignedDriverJobs=async session=>db.bookings.filter(row=>row.driver_id===session.driverId&&row.booking_date>=db.today).map(row=>portalDeps.toDriverJob(row,session));const work=await db.work.driverHomeWork({...db.session,driverId:'27'});const normalized=ops.driverHomeJobs(work.map(row=>row.job),Object.fromEntries(work.map(row=>[row.job.id,row.events])),db.today,'27');assert.equal(normalized.nextJob.id,ids[0]);assert.equal(normalized.currentJob.id,ids[0]);assert.equal(normalized.remainingTodayCount,0)});
