const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
function load(file, deps = {}) {
  const m = { exports: {} };
  const source = fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
  const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
  new Function('require', 'module', 'exports', js)(name => {
    if (name === './driver-route-options') return load('components/driver/driver-route-options.tsx', deps);
    if (name === './driver-disclosure') return load('components/driver/driver-disclosure.tsx', deps);
    if (name in deps) return deps[name];
    return require(name);
  }, m, m.exports);
  return m.exports;
}
const ops = load('lib/driver-operations.ts');
const today = '2026-10-06';
const job = (id, date = today, time = '13:30') => ({ id, bookingDate: date, pickupTime: time, clientName: id, pickupName: 'QMB', dropoffName: 'BKK', driverId: 'own', vehicleRegistration: '1998' });
const event = (eventType, hour = 9) => ({ eventType, eventTime: `2026-10-06T${String(hour).padStart(2,'0')}:00:00+07:00`, latitude: null, longitude: null });
const done = event('job_completed');
const derive = (jobs, events = {}) => ops.driverHomeJobs(jobs, events, today, 'own');
function accountForToday(state) {
  assert.equal(state.remainingTodayCount, state.additionalTodayJobs.length + Number(state.nextJob?.bookingDate === today));
  const shown = [state.nextJob, ...state.upcomingGroups.flatMap(([,group])=>group)].filter(Boolean);
  assert.equal(new Set(shown.map(j=>j.id)).size, shown.length);
  assert.deepEqual(shown.map(j=>j.id).sort(), state.normalizedJobs.map(j=>j.id).sort());
}
test('A: two today jobs and tomorrow agree across count, Next Job and Today/Tomorrow groups', () => {
  const s=derive([job('B',today,'16:00'),job('C','2026-10-07','09:00'),job('A')]);
  assert.equal(s.remainingTodayCount,2);assert.equal(s.nextJob.id,'A');assert.deepEqual(s.upcomingGroups.map(([d,j])=>[d,j.map(x=>x.id)]),[[today,['B']],['2026-10-07',['C']]]);accountForToday(s);
});
test('B: single today job has no empty Today group',()=>{const s=derive([job('A')]);assert.equal(s.remainingTodayCount,1);assert.equal(s.nextJob.id,'A');assert.equal(s.upcomingGroups.length,0);accountForToday(s)});
test('C: tomorrow Next Job stays visible and is not duplicated',()=>{const s=derive([job('A','2026-10-07','09:00')]);assert.equal(s.remainingTodayCount,0);assert.equal(s.nextJob.id,'A');assert.equal(s.upcomingGroups.length,0);accountForToday(s)});
test('D/J: timed jobs sort before untimed jobs, unless an untimed job is active',()=>{const jobs=[job('B',today,null),job('A')];const s=derive(jobs);assert.equal(s.remainingTodayCount,2);assert.equal(s.nextJob.id,'A');assert.equal(s.additionalTodayJobs[0].id,'B');accountForToday(s);const active=derive(jobs,{B:[event('pickup_arrived')]});assert.equal(active.nextJob.id,'B');accountForToday(active)});
test('E: completed, cancelled, rejected and foreign jobs cannot enter any Home section',()=>{const jobs=[job('A'),job('B'),{...job('cancelled'),bookingStatus:'Cancelled'},{...job('rejected'),bookingStatus:'rejected'},{...job('foreign'),driverId:'other'},{...job('office-done'),bookingStatus:'Completed'}];const s=derive(jobs,{A:[done]});assert.equal(s.remainingTodayCount,1);assert.deepEqual(s.normalizedJobs.map(j=>j.id),['B']);accountForToday(s)});
test('F: an active job wins over an earlier scheduled job and stays until actual completion',()=>{const jobs=[job('active',today,'16:00'),job('earlier',today,'09:00')];for(const type of ['pickup_arrived','pickup_departed','delivery_arrived']){const s=derive(jobs,{active:[event(type)]});assert.equal(s.nextJob.id,'active');assert.equal(s.remainingTodayCount,2);accountForToday(s)}const s=derive(jobs,{active:[done]});assert.equal(s.nextJob.id,'earlier');assert.equal(s.remainingTodayCount,1);accountForToday(s)});
test('G: Bangkok date-only keys and month/year rollover never depend on device timezone',()=>{for(const zone of ['Asia/Bangkok','America/Los_Angeles','Pacific/Auckland']){const previous=process.env.TZ;try{process.env.TZ=zone;assert.equal(ops.nextBangkokDate('2026-10-06'),'2026-10-07');assert.equal(ops.nextBangkokDate('2026-12-31'),'2027-01-01');assert.equal(derive([job('A')]).nextJob.bookingDate,today)}finally{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous}}});
test('H: identical schedules use deterministic IDs and duplicate rows never inflate counts',()=>{const jobs=[job('B'),job('A'),job('A')];const snapshot=JSON.stringify(jobs);assert.equal(derive(jobs).nextJob.id,'A');assert.equal(derive([...jobs].reverse()).nextJob.id,'A');assert.equal(derive(jobs).remainingTodayCount,2);assert.equal(JSON.stringify(jobs),snapshot)});
test('I: future Next Job has no today requirement or future cutoff',()=>{const s=derive([job('A','2026-10-08')]);assert.equal(s.remainingTodayCount,0);assert.equal(s.nextJob.bookingDate,'2026-10-08');accountForToday(s)});
test('an active job already in the collection remains current across Bangkok midnight',()=>{const s=derive([job('old','2026-10-05'),job('today')],{old:[event('pickup_departed')]});assert.equal(s.nextJob.id,'old');assert.equal(s.remainingTodayCount,1);assert.equal(s.additionalTodayJobs[0].id,'today')});
for(const language of ['en','th'])test(`Home presents Today, Tomorrow, date-only labels and future context in ${language}`,()=>{const deps={react:{...React,useState:()=>[null,()=>{}]},'next/image':({fill,priority,sizes,...p})=>React.createElement('img',p),'next/link':({children,...p})=>React.createElement('a',p,children),'@/lib/language-provider':{useLanguage:()=>({language})},'@/lib/driver-operations':ops,'@/lib/driver-vehicle-types':load('lib/driver-vehicle-types.ts'),'./driver-ui':load('components/driver/driver-ui.tsx')};const {DriverHome}=load('components/driver/driver-home.tsx',deps);const render=jobs=>renderToStaticMarkup(React.createElement(DriverHome,{driverName:'Joey Ryan',driverId:'own',today,jobs}));const html=render([job('A'),job('B',today,'16:00'),job('C','2026-10-07')]);assert.ok(html.includes(language==='en'?'>Today<':'>วันนี้<'));assert.ok(html.includes(language==='en'?'>Tomorrow<':'>พรุ่งนี้<'));assert.equal((html.match(/href="\/driver\/jobs\/A"/g)||[]).length,1);if(language==='en')assert.ok(html.includes('6 Oct 2026'));const future=render([job('A','2026-10-07')]);assert.ok(future.includes(language==='en'?'No more jobs today':'วันนี้ไม่มีงานเหลือแล้ว'));assert.ok(future.includes(language==='en'?'Tomorrow':'พรุ่งนี้'));assert.equal((future.match(/href="\/driver\/jobs\/A"/g)||[]).length,1)});
test('bilingual collapsed route options preserve verified segment, full route and active destination',()=>{const portal=load('lib/driver-portal.ts');const verified={...job('A'),locationsVerified:true,pickupLat:13.1,pickupLng:100.1,dropoffLat:13.2,dropoffLng:100.2,pickupPlaceId:'places/pickup-id',dropoffPlaceId:'places/drop-id'};const depot={name:'EES Depot',latitude:13,longitude:100,placeId:'places/depot-id'};const urls={};for(const [key,mode]of [['depot','depot'],['current','current'],['pickup','pickup'],['delivery','delivery'],['pickupToDropoff','pickup-to-dropoff']])urls[key]=portal.buildDriverDirectionsUrl(verified,mode,depot);const {DriverRouteOptions}=load('components/driver/driver-route-options.tsx');for(const language of ['en','th'])for(const defaultDestination of ['pickup','delivery']){const html=renderToStaticMarkup(React.createElement(DriverRouteOptions,{language,pickupName:'QMB',deliveryName:'BKK',defaultDestination,urls}));assert.ok(!html.includes('<details open'));const links=[...html.matchAll(/href="([^"]+)"/g)].map(m=>new URL(m[1].replaceAll('&amp;','&')));assert.equal(links.length,4);assert.equal(links[0].searchParams.get('origin_place_id'),'depot-id');assert.equal(links[0].searchParams.get('destination_place_id'),'pickup-id');assert.equal(links[0].searchParams.has('waypoints'),false);assert.equal(links[1].searchParams.get('origin_place_id'),'pickup-id');assert.equal(links[1].searchParams.get('destination_place_id'),'drop-id');assert.equal(links[2].searchParams.get('destination_place_id'),defaultDestination==='pickup'?'pickup-id':'drop-id');assert.equal(links[2].searchParams.has('origin'),false);assert.equal(links[3].searchParams.get('origin_place_id'),'depot-id');assert.equal(links[3].searchParams.get('waypoint_place_ids'),'pickup-id');assert.equal(links[3].searchParams.get('destination_place_id'),'drop-id')}});
test('Driver header and Profile contain no avatar, photo editing or file upload UI',()=>{for(const file of ['components/driver/driver-portal-header.tsx','components/driver/driver-profile.tsx']){const source=fs.readFileSync(path.join(__dirname,'..',file),'utf8');assert.doesNotMatch(source,/DriverAvatar|avatarUrl|type="file"|\/profile\/avatar|Change photo|เปลี่ยนรูป/)} });
test('server retains only owned, started, unfinished past assignments across midnight',async()=>{const calls=[];const rows=Array.from({length:501},(_,i)=>({id:'past-'+i,booking_date:'2026-10-05',driver_id:'own'}));const admin={from(table){assert.equal(table,'booking_diary');const q={select(fields){calls.push(['select',fields]);return q},eq(k,v){calls.push(['eq',k,v]);return q},lt(k,v){calls.push(['lt',k,v]);return q},is(k,v){calls.push(['is',k,v]);return q},order(){return q},async range(a,b){calls.push(['range',a,b]);return{data:rows.slice(a,b+1),error:null}}};return q}};class DriverPortalError extends Error{constructor(status,msg){super(msg);this.status=status}}const server=load('lib/driver-work-server.ts',{'server-only':{},'@/lib/admin-user-management-server':{},'@/lib/driver-portal-server':{bangkokDateKey:()=> '2026-10-07',DRIVER_JOB_SELECT:'id,driver_id,booking_date',DriverPortalError,toDriverJob:r=>({id:r.id,bookingDate:r.booking_date,driverId:r.driver_id})},'@/lib/driver-profile-server':{},'@/lib/driver-operations':ops});const result=await server.pastActiveDriverJobs(admin,{driverId:'own'},today);assert.equal(result.length,501);assert.ok(calls.some(([op,k,v])=>op==='eq'&&k==='driver_id'&&v==='own'));assert.ok(calls.some(([op,k,v])=>op==='eq'&&k==='started.driver_id'&&v==='own'));assert.ok(calls.some(([op,k,v])=>op==='eq'&&k==='started.event_type'&&v==='pickup_arrived'));assert.ok(calls.some(([op,k,v])=>op==='eq'&&k==='finished.event_type'&&v==='job_completed'));assert.ok(calls.some(([op,k,v])=>op==='is'&&k==='finished'&&v===null));assert.ok(calls.some(([op,k,v])=>op==='lt'&&k==='booking_date'&&v===today));assert.deepEqual(calls.filter(c=>c[0]==='range'),[['range',0,499],['range',500,999]]);const q={select(){return q},eq(){return q},lt(){return q},is(){return q},order(){return q},async range(){return{data:null,error:new Error('failed')}}};await assert.rejects(server.pastActiveDriverJobs({from:()=>q},{driverId:'own'}),{status:503})});
