"use client";

import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Boxes, CircleDollarSign, PackageOpen, Pencil, Plus, RefreshCw, Settings2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Header } from "@/components/header";
import { CategoryDialog, ItemDialog, MovementDialog } from "@/components/inventory-dialogs";
import { InventoryIssueDialog } from "@/components/inventory-issue-dialog";
import { InventoryMovementHistory } from "@/components/inventory-history";
import { fetchInventoryData, saveInventoryCategory, saveInventoryItem } from "@/lib/inventory-data";
import { inventoryDisplayName, inventoryStockStatus, inventorySummary } from "@/lib/inventory";
import type { InventoryCategory, InventoryData, InventoryItem } from "@/lib/inventory-types";
import { useLanguage } from "@/lib/language-provider";
import { useAccountAccess } from "@/lib/use-account-access";

const empty:InventoryData={categories:[],items:[],variants:[],movements:[],drivers:[],vehicles:[]};
export default function InventoryPage(){
 const {t,language}=useLanguage(),c=t.inventory,{can}=useAccountAccess(); const [data,setData]=useState<InventoryData>(empty),[busy,setBusy]=useState(true),[error,setError]=useState(""),[dialog,setDialog]=useState<"item"|"receive"|"adjust"|"issue"|"category"|"history"|null>(null),[selectedItem,setSelectedItem]=useState<InventoryItem|null>(null),[selectedCategory,setSelectedCategory]=useState<InventoryCategory|null>(null),[search,setSearch]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await fetchInventoryData())}catch(e){setError(`${c.errorLoad} ${String((e as Error).message??"")}`)}finally{setBusy(false)}},[c.errorLoad]);
 useEffect(()=>{void load()},[load]); const summary=useMemo(()=>inventorySummary(data),[data]);
 const driverById=useMemo(()=>new Map(data.drivers.map(driver=>[String(driver.id),driver])),[data.drivers]);
 const vehicleById=useMemo(()=>new Map(data.vehicles.map(vehicle=>[String(vehicle.id),vehicle])),[data.vehicles]);
 const shown=data.items.filter(item=>{const q=search.trim().toLowerCase();return !q||item.name.toLowerCase().includes(q)||item.name_th?.toLowerCase().includes(q)||item.sku?.toLowerCase().includes(q)});
 const attention=data.variants.filter(v=>{const item=data.items.find(i=>i.id===v.item_id);return item?.active&&inventoryStockStatus(v.current_quantity,v.minimum_stock)!=="ok"}).sort((a,b)=>a.current_quantity-b.current_quantity);
 const money=(n:number)=>new Intl.NumberFormat(language==="th"?"th-TH":"en-GB",{style:"currency",currency:"THB",maximumFractionDigits:2}).format(n);
 const date=(value:string)=>new Intl.DateTimeFormat(language==="th"?"th-TH":"en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
 const issueTypes=new Set(["issued_to_driver","issued_to_vehicle","general_use"]);
 const movementLabel=(type:string)=>type==="received"?c.received:type==="issued_to_driver"?c.issuedToDriver:type==="issued_to_vehicle"?c.issuedToVehicle:type==="general_use"?c.generalUse:type==="adjustment_plus"?c.adjustmentPlus:c.adjustmentMinus;
 const movementTarget=(movement:InventoryData["movements"][number])=>movement.driver_id?driverById.get(movement.driver_id)?.name:movement.vehicle_id?(vehicleById.get(movement.vehicle_id)?.vehicle_reg||vehicleById.get(movement.vehicle_id)?.registration):movement.movement_type==="general_use"?c.generalUse:null;
 async function saved(){setDialog(null);setSelectedItem(null);setSelectedCategory(null);await load()}
 async function archiveCategory(category:InventoryCategory){if(!confirm(c.confirmArchive))return;await saveInventoryCategory({...category,active:false},category.updated_at);await load()}
 async function archiveItem(item:InventoryItem){if(!confirm(c.archive+"?"))return;const variants=data.variants.filter(v=>v.item_id===item.id).map(v=>({id:v.id,name:v.name,sku:v.sku,is_default:v.is_default,minimum_stock:v.minimum_stock,average_cost:v.average_cost}));await saveInventoryItem({...item,active:false},variants,item.updated_at);await load()}
 return <div className="space-y-4"><Header title={c.title} description={c.description}/>
 <div className="flex flex-wrap items-center gap-2"><button className="btn-primary gap-2" disabled={!can("inventory.receive")} onClick={()=>setDialog("receive")}><ArrowDownToLine className="h-4 w-4"/>{c.receiveStock}</button>{can("inventory.issue")&&<button className="btn-primary gap-2 bg-[linear-gradient(135deg,#dc2626,#f97316)]" onClick={()=>setDialog("issue")}><ArrowUpFromLine className="h-4 w-4"/>{c.issueStock}</button>}{can("inventory.adjust")&&<button className="btn-secondary gap-2" onClick={()=>setDialog("adjust")}><Settings2 className="h-4 w-4"/>{c.adjustStock}</button>}{can("inventory.manage")&&<><button className="btn-secondary gap-2" onClick={()=>{setSelectedItem(null);setDialog("item")}}><Plus className="h-4 w-4"/>{c.addItem}</button><button className="btn-secondary gap-2" onClick={()=>{setSelectedCategory(null);setDialog("category")}}><Boxes className="h-4 w-4"/>{c.addCategory}</button></>}<button className="btn-secondary ml-auto gap-2" disabled={busy} onClick={()=>void load()}><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/>{c.refresh}</button></div>
 {error&&<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</div>}
 <section className="grid grid-cols-2 gap-2.5 lg:grid-cols-4">{[
  {label:c.totalItems,value:summary.totalItems,Icon:Boxes,tone:"text-indigo-700 bg-indigo-50 border-indigo-100"},
  {label:c.lowStock,value:summary.lowStock,Icon:AlertTriangle,tone:"text-amber-700 bg-amber-50 border-amber-100"},
  {label:c.outOfStock,value:summary.outOfStock,Icon:PackageOpen,tone:"text-rose-700 bg-rose-50 border-rose-100"},
  {label:c.stockValue,value:money(summary.stockValue),Icon:CircleDollarSign,tone:"text-emerald-700 bg-emerald-50 border-emerald-100"}
 ].map(({label,value,Icon,tone})=><div key={label} className={`rounded-2xl border p-3 shadow-sm ${tone}`}><div className="flex items-start justify-between gap-2"><p className="text-[11px] font-bold uppercase tracking-wide opacity-75">{label}</p><Icon className="h-4 w-4"/></div><p className="mt-2 text-xl font-black sm:text-2xl">{String(value)}</p></div>)}</section>
 <div className="grid gap-4 xl:grid-cols-2"><section className="surface-card p-4"><h2 className="section-title">{c.recentMovements}</h2><div className="mt-3 space-y-2">{data.movements.length===0?<p className="text-sm text-slate-500">{c.noMovements}</p>:data.movements.slice(0,8).map(m=>{const item=data.items.find(i=>i.id===m.item_id),variant=data.variants.find(v=>v.id===m.variant_id),issued=issueTypes.has(m.movement_type),target=movementTarget(m);return <div key={m.id} className="flex items-center justify-between gap-3 rounded-xl border border-violet-100 bg-violet-50/40 p-3"><div className="min-w-0"><p className="truncate font-semibold">{item?inventoryDisplayName(item,language):"—"}{variant&&!variant.is_default?` · ${variant.name}`:""}</p><p className="text-xs text-slate-500">{date(m.occurred_at)} · <span className={`rounded-full px-1.5 py-0.5 font-bold ${issued?"bg-rose-100 text-rose-700":"bg-emerald-100 text-emerald-700"}`}>{movementLabel(m.movement_type)}</span>{target?` · ${target}`:""}</p></div><div className="text-right"><p className={`font-black ${issued||m.movement_type==="adjustment_minus"?"text-rose-700":"text-emerald-700"}`}>{issued||m.movement_type==="adjustment_minus"?"−":"+"}{m.quantity}</p><p className="text-xs text-slate-500">{m.previous_quantity} → {m.new_quantity}</p></div></div>})}</div></section>
 <section className="surface-card p-4"><h2 className="section-title">{c.requiringAttention}</h2><div className="mt-3 space-y-2">{attention.length===0?<p className="text-sm text-slate-500">{c.noAttention}</p>:attention.slice(0,10).map(v=>{const item=data.items.find(i=>i.id===v.item_id)!;const status=inventoryStockStatus(v.current_quantity,v.minimum_stock);return <div key={v.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div><p className="font-semibold">{inventoryDisplayName(item,language)}{!v.is_default?` · ${v.name}`:""}</p><p className="text-xs text-slate-500">{c.minimumStock}: {v.minimum_stock} {item.unit}</p></div><div className="text-right"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${status==="out"?"bg-rose-100 text-rose-800":"bg-amber-100 text-amber-800"}`}>{status==="out"?c.statusOut:c.statusLow}</span><p className="mt-1 font-bold">{v.current_quantity} {item.unit}</p></div></div>})}</div></section></div>
 <section className="surface-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="section-title">{c.stockItems}</h2><p className="section-subtitle">{summary.totalItems} {c.totalItems}</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={c.searchItems} className="form-input w-full border sm:w-64"/></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{shown.length===0?<p className="text-sm text-slate-500">{c.noItems}</p>:shown.map(item=>{const variants=data.variants.filter(v=>v.item_id===item.id),category=data.categories.find(x=>x.id===item.category_id);return <article key={item.id} className="rounded-2xl border border-violet-100 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold text-slate-950">{inventoryDisplayName(item,language)}</p><p className="text-xs text-slate-500">{category?.name} {item.sku?`· ${item.sku}`:""}</p></div>{can("inventory.manage")&&<div className="flex gap-1"><button className="btn-icon h-9 w-9" onClick={()=>{setSelectedItem(item);setDialog("item")}} aria-label={c.edit}><Pencil className="h-4 w-4"/></button><button className="btn-action text-rose-700" onClick={()=>void archiveItem(item)}>{c.archive}</button></div>}</div><div className="mt-3 space-y-2">{variants.map(v=>{const status=inventoryStockStatus(v.current_quantity,v.minimum_stock);return <div key={v.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-2.5"><div><p className="text-sm font-semibold">{v.is_default?c.noVariant:v.name}</p><p className="text-[11px] text-slate-500">{c.minimumStock}: {v.minimum_stock}</p></div><div className="text-right"><p className="font-black">{v.current_quantity} {item.unit}</p>{status!=="ok"&&<span className={`text-[10px] font-black ${status==="out"?"text-rose-700":"text-amber-700"}`}>{status==="out"?c.statusOut:c.statusLow}</span>}</div></div>})}</div></article>})}</div></section>
 {can("inventory.manage")&&<section className="surface-card p-4"><h2 className="section-title">{c.categories}</h2><div className="mt-3 flex flex-wrap gap-2">{data.categories.map(category=><div key={category.id} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-sm ${category.active?"border-violet-100 bg-violet-50/50":"border-slate-200 bg-slate-50 text-slate-400"}`}><span>{language==="th"&&category.name_th?category.name_th:category.name}</span><button onClick={()=>{setSelectedCategory(category);setDialog("category")}} aria-label={c.edit}><Pencil className="h-3.5 w-3.5"/></button>{category.active&&<button className="text-rose-700" onClick={()=>void archiveCategory(category)}>{c.archive}</button>}</div>)}</div></section>}
 <InventoryMovementHistory data={data}/>
 {dialog==="item"&&<ItemDialog data={data} selected={selectedItem} onClose={()=>setDialog(null)} onSaved={()=>void saved()}/>} {dialog==="category"&&<CategoryDialog data={data} selected={selectedCategory} onClose={()=>setDialog(null)} onSaved={()=>void saved()}/>} {dialog==="issue"&&<InventoryIssueDialog data={data} onClose={()=>setDialog(null)} onSaved={()=>void saved()}/>} {(dialog==="receive"||dialog==="adjust")&&<MovementDialog data={data} mode={dialog} onClose={()=>setDialog(null)} onSaved={()=>void saved()}/>}</div>
}
