"use client";

import { Plus, Trash2, X } from "lucide-react";
import { useRef, useState, type FormEvent, type ReactNode } from "react";
import { adjustInventoryStock, receiveInventoryStock, saveInventoryCategory, saveInventoryItem } from "@/lib/inventory-data";
import { INVENTORY_UNITS, type InventoryCategory, type InventoryData, type InventoryItem, type InventoryVariant } from "@/lib/inventory-types";
import { useLanguage } from "@/lib/language-provider";

function Dialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const { t } = useLanguage();
  return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/40 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label={title}>
    <div className="max-h-[94vh] w-full overflow-y-auto rounded-t-3xl border border-violet-100 bg-white p-4 shadow-2xl sm:max-w-3xl sm:rounded-3xl sm:p-6">
      <div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-xl font-bold text-slate-950">{title}</h2><button type="button" className="btn-icon h-11 w-11" onClick={onClose} aria-label={t.common.cancel}><X className="h-5 w-5"/></button></div>
      {children}
    </div>
  </div>;
}
function Field({ label, children, required=false }: { label: string; children: ReactNode; required?: boolean }) { return <label className="form-field"><span className={`form-label ${required ? "form-label-required" : ""}`}>{label}</span>{children}</label>; }
const input = "form-input w-full border bg-white";
const text = (value: FormDataEntryValue | null) => String(value ?? "").trim();
const number = (value: FormDataEntryValue | null) => Number(value || 0);

export function CategoryDialog({ selected, onClose, onSaved }: { data: InventoryData; selected?: InventoryCategory | null; onClose: () => void; onSaved: () => void }) {
  const { t } = useLanguage(), c=t.inventory; const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{await saveInventoryCategory({id:selected?.id??crypto.randomUUID(),name:text(form.get("name")),name_th:text(form.get("name_th"))||null,description:text(form.get("description"))||null,active:selected?.active??true},selected?.updated_at??null);onSaved();}catch{setError(c.errorSave)}finally{setBusy(false)}}
  return <Dialog title={selected?c.editCategory:c.addCategory} onClose={onClose}><form className="space-y-4" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><Field label={c.categoryName} required><input name="name" required maxLength={120} defaultValue={selected?.name} className={input}/></Field><Field label={c.categoryThaiName}><input name="name_th" maxLength={120} defaultValue={selected?.name_th??""} className={input}/></Field></div><Field label={c.descriptionLabel}><textarea name="description" defaultValue={selected?.description??""} className="form-textarea min-h-24 w-full border"/></Field>{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>{c.cancel}</button><button disabled={busy} className="btn-primary">{busy?c.saving:c.save}</button></div></form></Dialog>;
}

type VariantDraft={id:string;name:string;sku:string;minimum_stock:number;average_cost:number};
export function ItemDialog({ data, selected, onClose, onSaved }: { data: InventoryData; selected?: InventoryItem|null; onClose:()=>void; onSaved:()=>void }) {
 const {t,language}=useLanguage(),c=t.inventory; const existing=selected?data.variants.filter(v=>v.item_id===selected.id):[];
 const [variants,setVariants]=useState<VariantDraft[]>(existing.length?existing.map(v=>({id:v.id,name:v.name??"",sku:v.sku??"",minimum_stock:v.minimum_stock,average_cost:v.average_cost})):[{id:crypto.randomUUID(),name:"",sku:"",minimum_stock:0,average_cost:0}]);
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const update=(index:number,patch:Partial<VariantDraft>)=>setVariants(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
 const history=selected?data.movements.filter(movement=>movement.item_id===selected.id):[];
 const movementCopy=(type:string)=>type==="received"?c.received:type==="issued_to_driver"?(language==="th"?"จ่ายให้คนขับ":"Given to Driver"):type==="issued_to_vehicle"?(language==="th"?"จ่ายให้รถ":"Given to Vehicle"):type==="general_use"?c.generalUse:type==="adjustment_plus"?(language==="th"?"เพิ่มสต็อก":"Stock Added"):(language==="th"?"ลดสต็อก":"Stock Removed");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(variants.length>1&&variants.some(v=>!v.name.trim())){setError(c.errorSave);return}setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const id=selected?.id??crypto.randomUUID();await saveInventoryItem({id,category_id:text(form.get("category_id")),name:text(form.get("name")),name_th:text(form.get("name_th"))||null,sku:text(form.get("sku"))||null,description:text(form.get("description"))||null,unit:text(form.get("unit")),reorder_quantity:number(form.get("reorder_quantity")),preferred_supplier:text(form.get("preferred_supplier"))||null,storage_location:text(form.get("storage_location"))||null,notes:text(form.get("notes"))||null,active:selected?.active??true},variants.map((v)=>({...v,name:v.name.trim()||null,sku:v.sku.trim()||null,is_default:variants.length===1&&!v.name.trim()})),selected?.updated_at??null);onSaved()}catch{setError(c.errorSave)}finally{setBusy(false)}}
 return <Dialog title={selected?c.itemDetails:c.addItem} onClose={onClose}><form className="space-y-5" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><Field label={c.itemName} required><input name="name" required maxLength={200} defaultValue={selected?.name} className={input}/></Field><Field label={c.thaiName}><input name="name_th" maxLength={200} defaultValue={selected?.name_th??""} className={input}/></Field><Field label={c.category} required><select name="category_id" required defaultValue={selected?.category_id??""} className={input}><option value="">{c.category}</option>{data.categories.filter(x=>x.active||x.id===selected?.category_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label={c.sku}><input name="sku" defaultValue={selected?.sku??""} className={input}/></Field><Field label={c.unit} required><select name="unit" defaultValue={selected?.unit??"piece"} className={input}>{INVENTORY_UNITS.map(unit=><option key={unit} value={unit}>{c.units[unit]}</option>)}</select></Field><Field label={c.reorderQuantity}><input name="reorder_quantity" type="number" min="0" step="0.001" defaultValue={selected?.reorder_quantity??0} className={input}/></Field><Field label={c.preferredSupplier}><input name="preferred_supplier" defaultValue={selected?.preferred_supplier??""} className={input}/></Field><Field label={c.storageLocation}><input name="storage_location" defaultValue={selected?.storage_location??""} className={input}/></Field></div><Field label={c.descriptionLabel}><textarea name="description" defaultValue={selected?.description??""} className="form-textarea min-h-20 w-full border"/></Field>
 <section className="rounded-2xl border border-violet-100 bg-violet-50/50 p-3"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{language === "th" ? "ขนาด / ตัวเลือก" : "Sizes / Options"}</h3><p className="text-xs text-slate-500">{c.variantHelp}</p></div><button type="button" className="btn-action" onClick={()=>setVariants(v=>[...v,{id:crypto.randomUUID(),name:"",sku:"",minimum_stock:0,average_cost:0}])}><Plus className="h-4 w-4"/>{language === "th" ? "เพิ่มขนาด / ตัวเลือก" : "Add Size / Option"}</button></div><div className="mt-3 space-y-3">{variants.map((v,index)=><div key={v.id} className="grid gap-2 rounded-xl border bg-white p-3 sm:grid-cols-[1.2fr_1fr_1fr_1fr_auto]"><Field label={language === "th" ? "ขนาด / ตัวเลือก" : "Size / Option"}><input value={v.name} onChange={e=>update(index,{name:e.target.value})} placeholder={variants.length===1?c.noVariant:""} className={input}/></Field><Field label={c.sku}><input value={v.sku} onChange={e=>update(index,{sku:e.target.value})} className={input}/></Field><Field label={c.minimumStock}><input type="number" min="0" step="0.001" value={v.minimum_stock} onChange={e=>update(index,{minimum_stock:Number(e.target.value)})} className={input}/></Field><Field label={c.unitCost}><input type="number" min="0" step="0.0001" value={v.average_cost} onChange={e=>update(index,{average_cost:Number(e.target.value)})} className={input}/></Field><button type="button" disabled={variants.length===1} className="btn-icon mt-6 h-11 w-11 disabled:opacity-30" onClick={()=>setVariants(rows=>rows.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/></button></div>)}</div></section>
 {selected?<section className="rounded-2xl border border-violet-100 p-3"><h3 className="font-bold">{c.history}</h3><div className="mt-2 max-h-52 space-y-2 overflow-y-auto">{history.length===0?<p className="text-sm text-slate-500">{c.noMovements}</p>:history.map(movement=>{const variant=data.variants.find(value=>value.id===movement.variant_id),driver=data.drivers.find(value=>String(value.id)===movement.driver_id),vehicle=data.vehicles.find(value=>String(value.id)===movement.vehicle_id),issued=movement.movement_type.startsWith("issued")||movement.movement_type==="general_use";return <div key={movement.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-2.5 text-sm"><div><strong>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(movement.occurred_at))} · {movementCopy(movement.movement_type)}</strong><p className="text-xs text-slate-500">{variant&&!variant.is_default?variant.name:""} {driver?.name||vehicle?.vehicle_reg||(movement.movement_type==="general_use"?c.generalUse:"")}</p></div><strong className={issued?"text-violet-700":"text-emerald-700"}>{issued?"−":"+"}{movement.quantity}</strong></div>})}</div></section>:null}
 <Field label={c.notes}><textarea name="notes" defaultValue={selected?.notes??""} className="form-textarea min-h-20 w-full border"/></Field>{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>{c.cancel}</button><button disabled={busy} className="btn-primary">{busy?c.saving:c.save}</button></div></form></Dialog>;
}

export function MovementDialog({ data, mode, onClose, onSaved }: { data:InventoryData; mode:"receive"|"adjust"; onClose:()=>void; onSaved:()=>void }) {
 const {t,language}=useLanguage(),c=t.inventory; const [itemId,setItemId]=useState(""),[variantId,setVariantId]=useState(""),[quantity,setQuantity]=useState(1),[unitCost,setUnitCost]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""); const requestId=useRef(crypto.randomUUID());
 const items=data.items.filter(i=>i.active); const variants=data.variants.filter(v=>v.item_id===itemId); const item=data.items.find(i=>i.id===itemId); const selected=data.variants.find(v=>v.id===variantId);
 const total=quantity*unitCost;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const movementType=mode==="receive"?"received":text(form.get("movement_type"));if(movementType==="adjustment_minus"&&selected&&quantity>selected.current_quantity){setError(c.errorNegative);setBusy(false);return}const payload={request_id:requestId.current,occurred_at:new Date(text(form.get("date"))).toISOString(),variant_id:variantId,quantity,unit_cost:mode==="receive"?unitCost:null,supplier:text(form.get("supplier")),storage_location:text(form.get("storage_location")),reference_number:text(form.get("reference_number")),notes:text(form.get("notes")),movement_type:movementType};try{if(mode==="receive")await receiveInventoryStock(payload);else await adjustInventoryStock(payload);onSaved()}catch(e){setError(String((e as Error)?.message||"").includes("NEGATIVE")?c.errorNegative:c.errorSave)}finally{setBusy(false)}}
 return <Dialog title={mode==="receive"?c.receiveStock:c.adjustStock} onClose={onClose}><form className="space-y-4" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><Field label={c.date} required><input name="date" type="datetime-local" required defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)} className={input}/></Field>{mode==="adjust"&&<Field label={c.movementType} required><select name="movement_type" className={input}><option value="adjustment_plus">{language === "th" ? "เพิ่มสต็อก" : "Stock Added"}</option><option value="adjustment_minus">{language === "th" ? "ลดสต็อก" : "Stock Removed"}</option></select></Field>}<Field label={c.itemName} required><select value={itemId} required onChange={e=>{setItemId(e.target.value);setVariantId("")}} className={input}><option value="">{c.selectItem}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field><Field label={language === "th" ? "ขนาด / ตัวเลือก" : "Size / Option"} required><select value={variantId} required disabled={!itemId} onChange={e=>setVariantId(e.target.value)} className={input}><option value="">{language === "th" ? "เลือกขนาด / ตัวเลือก" : "Select size / option"}</option>{variants.map(v=><option key={v.id} value={v.id}>{v.is_default?c.noVariant:v.name} · {v.current_quantity}</option>)}</select></Field><Field label={c.quantity} required><input type="number" min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required className={input}/></Field>{mode==="receive"&&<><Field label={c.unitCost} required><input type="number" min="0" step="0.0001" value={unitCost} onChange={e=>setUnitCost(Number(e.target.value))} required className={input}/></Field><Field label={c.totalCost}><output className="form-input-readonly block">{new Intl.NumberFormat(undefined,{style:"currency",currency:"THB"}).format(total)}</output></Field><Field label={c.supplier}><input name="supplier" defaultValue={item?.preferred_supplier??""} className={input}/></Field><Field label={c.referenceNumber}><input name="reference_number" className={input}/></Field></>}<Field label={c.storageLocation}><input name="storage_location" defaultValue={item?.storage_location??""} className={input}/></Field></div><Field label={c.notes}><textarea name="notes" className="form-textarea min-h-20 w-full border"/></Field>{selected&&<p className="rounded-xl bg-violet-50 p-3 text-sm font-semibold text-violet-900">{c.currentStock}: {selected.current_quantity} {item?.unit}</p>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>{c.cancel}</button><button disabled={busy||!variantId} className="btn-primary min-w-32">{busy?c.saving:(mode==="receive"?c.receiveStock:c.adjustStock)}</button></div></form></Dialog>;
}
