"use client";
import { useMemo } from "react";
import Link from "next/link";
import { useLanguage } from "@/lib/language-provider";
import { maintenanceCostIntelligence } from "@/lib/maintenance-intelligence";
import { maintenanceCategoryLabels } from "@/lib/maintenance-translations";
import type { MaintenanceData } from "@/lib/maintenance-types";
import { formatCurrency, formatDate } from "@/lib/utils";

export function MaintenanceCostIntelligence({ data, vehicleIds, start, end }: { data: MaintenanceData; vehicleIds: string[]; start: string; end: string }) {
  const { t, language } = useLanguage(), c = t.maintenance;
  const stats = useMemo(() => maintenanceCostIntelligence(data, vehicleIds, start, end), [data, vehicleIds, start, end]);
  const money = (n: number | null) => n === null ? c.insufficient : formatCurrency(n, language);
  const registration = (id: string) => data.vehicles.find(v => v.id === id)?.vehicle_reg ?? "—";
  const list = (title: string, rows: { name: string; total: number; visits: number }[], category = false) => {const max=rows[0]?.total||1;return <section className="min-w-0 space-y-2 rounded-xl border border-violet-100 bg-[#faf9fe] p-3"><h4 className="font-semibold">{title}</h4>{!rows.length&&<p className="text-sm text-slate-500">{c.empty}</p>}<div className="max-h-72 overflow-y-auto">{rows.map((row,index) => <div key={`${row.name}:${index}`} className="relative border-b border-slate-100 py-2 text-sm"><span className="absolute bottom-1 left-0 top-1 rounded bg-violet-100/45" style={{width:`${Math.max(3,row.total/max*100)}%`}}/><div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words">{category ? maintenanceCategoryLabels[language][row.name as keyof typeof maintenanceCategoryLabels.en] : row.name||c.unassigned}</p><p className="text-xs text-slate-500">{row.visits} {c.visits}</p></div><strong className="shrink-0">{money(row.total)}</strong></div></div>)}</div></section>;};
  const highest=stats.vehicles.find(v=>v.visits>0),frequent=[...stats.vehicles].filter(v=>v.visits>0).sort((a,b)=>b.visits-a.visits||b.total-a.total)[0];
  return <section className="maintenance-panel space-y-4 p-4 sm:p-5">
    <h3 className="section-title">{c.costIntelligence}</h3><p className="text-xs text-slate-500">{c.intelligencePeriod}</p>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[c.spending,stats.total],[c.thisMonthSpend,stats.month],[c.thisYearSpend,stats.year],[c.averageVisit,stats.average]].map(([label,value])=><div key={String(label)} className="min-w-0 rounded-xl border border-violet-100 bg-violet-50/70 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-bold text-violet-950">{money(value as number|null)}</p>{label===c.thisMonthSpend&&stats.monthChange!==null&&<p className="mt-1 text-xs text-slate-500">{stats.monthChange>0?"↑":"↓"} {Math.abs(stats.monthChange).toFixed(0)}% {c.previousMonthComparison}</p>}</div>)}</div>
    <div className="grid gap-3 sm:grid-cols-2">{highest&&<div className="rounded-xl border border-violet-100 bg-white/65 p-3"><p className="text-xs text-slate-500">{c.highestSpend}</p><p className="mt-1 font-bold">{registration(highest.vehicleId)} · {money(highest.total)}</p></div>}{frequent&&<div className="rounded-xl border border-violet-100 bg-white/65 p-3"><p className="text-xs text-slate-500">{c.frequentVehicles}</p><p className="mt-1 font-bold">{registration(frequent.vehicleId)} · {frequent.visits} {c.visits}</p></div>}</div>
    <h4 className="font-semibold">{c.vehicleCostRanking}</h4>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr>{[c.vehicle,c.spending,c.visits,c.averageVisit,c.maintenanceKm,c.maintenance10000Km,c.latestService,c.upcoming].map(label=><th scope="col" className="px-2 py-2" key={label}>{label}</th>)}</tr></thead><tbody>{stats.vehicles.map(row=><tr key={row.vehicleId} className="border-b border-slate-100"><td className="whitespace-nowrap px-2 py-3"><Link className="font-semibold text-violet-700 underline" href={`/maintenance?vehicle=${row.vehicleId}`}>{registration(row.vehicleId)}</Link></td>{[money(row.total),row.visits,money(row.average),money(row.maintenancePerKm),money(row.maintenancePer10000Km),row.lastMaintenance?formatDate(row.lastMaintenance,language):"—",`${c.overdue}: ${row.overdue} · ${c.dueSoon}: ${row.upcoming}`].map((value,i)=><td key={i} className="px-2 py-3 align-top">{value}</td>)}</tr>)}</tbody></table></div>
    <div className="grid gap-3 lg:grid-cols-2">{list(c.categorySpending,stats.categories,true)}{list(c.supplierSpend,stats.garages)}{list(c.commonItems,stats.items)}{list(c.frequentVehicles,[...stats.vehicles].filter(v=>v.visits>0).sort((a,b)=>b.visits-a.visits||b.total-a.total).map(v=>({name:registration(v.vehicleId),total:v.total,visits:v.visits})))}</div>
    <details><summary className="cursor-pointer py-2 font-semibold">{c.recurringTrends} ({stats.repeats.length})</summary><p className="my-2 text-xs text-slate-500">{c.recurrenceHelp}</p>{!stats.repeats.length&&<p className="text-sm">{c.noRepeats}</p>}{stats.repeats.map(r=><div key={`${r.vehicleId}:${r.category}:${r.name}`} className="border-b border-slate-100 py-2 text-sm"><strong>{registration(r.vehicleId)}</strong> · {r.categoryFallback?maintenanceCategoryLabels[language][r.category]:r.name} · {r.visits} {c.occurrences} · {money(r.total)}<p className="text-xs text-slate-500">{formatDate(r.first,language)} – {formatDate(r.last,language)}</p></div>)}</details>
  </section>;
}
