"use client";
import { maintenanceVehicleType } from "@/lib/maintenance-ux";
import {useMemo,useRef,useState,type FormEvent} from "react";
import {buildMaintenanceReminders} from "@/lib/maintenance";
import {formatDate,formatNumber} from "@/lib/utils";
import {useLanguage} from "@/lib/language-provider";
import {useAccountAccess} from "@/lib/use-account-access";
import {saveMaintenanceRequirement} from "@/lib/maintenance-data";
import type {MaintenanceData,MaintenanceRequirement} from "@/lib/maintenance-types";
import {maintenanceCategoryLabels} from "@/lib/maintenance-translations";
import {MaintenanceField as Field,MaintenanceCategorySelect} from "./maintenance-fields";
export function MaintenanceRequirements({data,onSaved}:{data:MaintenanceData;onSaved:()=>void}) {
 const {t,language}=useLanguage(),c=t.maintenance,{can}=useAccountAccess();const [edit,setEdit]=useState<Partial<MaintenanceRequirement>|null>(null),[ids,setIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(false);const lock=useRef(false);
 const reminders=useMemo(()=>buildMaintenanceReminders(data),[data]);
 const start=(r?:MaintenanceRequirement)=>{setError(false);setEdit(r?{...r}:{id:crypto.randomUUID(),name:"",category:"other",vehicle_type:null,frequency_months:null,mileage_interval:null,warning_days:30,warning_km:1000,active:true,notes:null});setIds(r?data.applicability.filter(a=>a.requirement_id===r.id).map(a=>a.vehicle_id):[]);};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(lock.current||!edit)return;if((!ids.length&&!edit.vehicle_type)||(!edit.frequency_months&&!edit.mileage_interval)){setError(true);return;}lock.current=true;setBusy(true);setError(false);try{await saveMaintenanceRequirement(edit,ids,edit.updated_at??null);setEdit(null);onSaved();}catch{setError(true);}finally{setBusy(false);lock.current=false;}};
 return <section className="surface-card space-y-4 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="section-title">{c.requirements}</h3>{can("admin:user_management")&&<button className="btn-secondary" onClick={()=>start()}>{c.configure}</button>}</div><p className="text-sm text-slate-500">{c.enabledOnly}</p><p className="text-xs text-slate-500">{c.requirementFirst} {c.monthlyRuleHelp}</p>{!data.requirements.length&&<p>{c.noRequirements}</p>}{data.requirements.map(r=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3" key={r.id}><div><strong>{r.name}</strong><p className="text-sm text-slate-500">{maintenanceCategoryLabels[language][r.category]} · {r.active?c.active:c.requirementDisabled} · {r.frequency_months??"—"} {c.months} · {r.mileage_interval??"—"} km</p><p className="text-xs text-slate-500">{maintenanceVehicleType(r.vehicle_type,t.weeklyMileage.oil.vehicleTypes)} {data.applicability.filter(a=>a.requirement_id===r.id).map(a=>data.vehicles.find(v=>v.id===a.vehicle_id)?.vehicle_reg).join(", ")}</p>{r.notes&&<p className="text-xs text-slate-600">{r.notes}</p>}<details><summary className="cursor-pointer py-2 text-xs text-violet-700">{c.lastCompleted} / {c.nextRequirement}</summary><div className="space-y-2">{reminders.filter(reminder=>reminder.key.endsWith(`:requirement:${r.id}`)).map(reminder=>{const last=data.records.find(record=>record.id===reminder.record_id);return <p className="text-xs" key={reminder.key}>{data.vehicles.find(v=>v.id===reminder.vehicle_id)?.vehicle_reg} · {c[reminder.status]} · {c.lastCompleted}: {last?formatDate(last.service_date,language):"—"} / {last?.odometer==null?"—":formatNumber(last.odometer,language)} · {c.nextDate}: {reminder.due_date?formatDate(reminder.due_date,language):"—"} · {c.nextMileage}: {reminder.due_km===null?"—":formatNumber(reminder.due_km,language)}</p>;})}</div></details></div>{can("admin:user_management")&&<button className="btn-secondary" onClick={()=>start(r)}>{c.editRequirement}</button>}</div>)}
 {edit&&<form onSubmit={submit} className="space-y-4 rounded-2xl border border-violet-200 p-4">{error&&<p role="alert" className="text-rose-700">{c.saveError} {c.scopeHint}</p>}<fieldset disabled={busy} className="space-y-4"><button type="button" className="btn-secondary" onClick={()=>setEdit({...edit,name:language==="th"?"จาระบีประจำปี":"Annual Grease",category:"grease",frequency_months:12,mileage_interval:null,warning_days:30})}>{c.annualExample}</button><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
 <Field label={c.requirementName}><input required maxLength={200} className="form-input" value={edit.name??""} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label={c.category}><MaintenanceCategorySelect value={edit.category??"other"} onChange={category=>setEdit({...edit,category})}/></Field><Field label={c.vehicleType}><select className="form-input" value={edit.vehicle_type??""} onChange={e=>setEdit({...edit,vehicle_type:e.target.value||null})}><option value="">{c.select}</option>{Array.from(new Set(data.vehicles.map(v=>v.vehicle_type).filter(Boolean))).map(type=><option key={type} value={type!}>{maintenanceVehicleType(type,t.weeklyMileage.oil.vehicleTypes)}</option>)}</select></Field>
 <Field label={c.months}><input type="number" min={1} max={1200} step={1} className="form-input" value={edit.frequency_months??""} onChange={e=>setEdit({...edit,frequency_months:e.target.value?Number(e.target.value):null})}/></Field><Field label={c.mileageInterval}><input type="number" min="0.01" max="9999999999.99" step="0.01" className="form-input" value={edit.mileage_interval??""} onChange={e=>setEdit({...edit,mileage_interval:e.target.value?Number(e.target.value):null})}/></Field><Field label={c.warningDays}><input required type="number" min={0} max={3650} step={1} className="form-input" value={edit.warning_days??30} onChange={e=>setEdit({...edit,warning_days:Number(e.target.value)})}/></Field><Field label={c.warningKm}><input required type="number" min={0} max="9999999999.99" step="0.01" className="form-input" value={edit.warning_km??1000} onChange={e=>setEdit({...edit,warning_km:Number(e.target.value)})}/></Field>
 </div><p className="text-sm text-slate-500">{c.scopeHint}</p><div className="grid max-h-64 gap-2 overflow-auto rounded-xl border p-3 sm:grid-cols-2 lg:grid-cols-3">{data.vehicles.map(v=><label key={v.id} className="flex min-h-10 items-center gap-2 text-sm"><input className="!h-4 !w-4 shrink-0" type="checkbox" checked={ids.includes(v.id)} onChange={e=>setIds(e.target.checked?[...ids,v.id]:ids.filter(id=>id!==v.id))}/>{v.vehicle_reg}</label>)}</div><Field label={c.notes}><textarea className="form-input" maxLength={10000} value={edit.notes??""} onChange={e=>setEdit({...edit,notes:e.target.value||null})}/></Field><label className="flex items-center gap-2"><input type="checkbox" className="!h-4 !w-4" checked={edit.active??true} onChange={e=>setEdit({...edit,active:e.target.checked})}/>{c.active}</label><div className="flex gap-2"><button className="btn-primary" type="submit">{busy?t.common.saving:c.saveRequirement}</button><button className="btn-secondary" type="button" onClick={()=>setEdit(null)}>{c.cancel}</button></div></fieldset></form>}
 </section>;
}
