"use client";
import { useRef,useState,type FormEvent } from "react";
import { useLanguage } from "@/lib/language-provider";
import { useAccountAccess } from "@/lib/use-account-access";
import { maintenanceLineTotal,maintenanceToday,maintenanceTotal,newMaintenanceItem,receiptDifference,validMaintenanceDate,maintenanceDriver } from "@/lib/maintenance";
import { saveMaintenanceRecord } from "@/lib/maintenance-data";
import { duplicateMaintenanceItem } from "@/lib/maintenance-intelligence";
import { reliableMaintenanceMileage } from "@/lib/maintenance";
import { formatCurrency,formatDate,formatNumber } from "@/lib/utils";
import type { MaintenanceData,MaintenanceRecord,MaintenanceRecordInput } from "@/lib/maintenance-types";
import { MaintenanceField as Field,MaintenanceCategorySelect } from "./maintenance-fields";
import { MaintenanceAttachmentList,MaintenanceUploader } from "./maintenance-attachments";

import { MaintenanceReminderFields, modeFor, type ItemForm } from "./maintenance-reminder-fields";
const timeInput=(value:string|null)=>value?new Date(Date.parse(value)+7*3600000).toISOString().slice(0,16):"";
const timeValue=(value:string)=>value?new Date(`${value}:00+07:00`).toISOString():null;
export function MaintenanceRecordForm({data,record,vehicleId,onClose,onSaved}:{data:MaintenanceData;record:MaintenanceRecord|null;vehicleId:string;onClose:()=>void;onSaved:()=>void}) {
 const {t,language}=useLanguage(),c=t.maintenance,{can}=useAccountAccess();const [savedRecord,setSavedRecord]=useState(record);
 const [form,setForm]=useState<MaintenanceRecordInput>(()=>record?{...record}:{id:crypto.randomUUID(),vehicle_id:vehicleId,service_date:maintenanceToday(),odometer:null,garage:null,receipt_reference:null,receipt_total:null,mismatch_confirmed:false,notes:null,off_road_at:null,returned_at:null});
 const [items,setItems]=useState<ItemForm[]>(()=>record?data.items.filter(i=>i.record_id===record.id).sort((a,b)=>a.position-b.position).map(i=>({...i,mode:modeFor(i)})):[{...newMaintenanceItem(crypto.randomUUID()),mode:"none"}]);
 const [uploadState,setUploadState]=useState({busy:false,pending:0}),[justSaved,setJustSaved]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState<"saveError"|"invalid"|"conflict"|null>(null);const lock=useRef(false);
 const set=(patch:Partial<MaintenanceRecordInput>)=>setForm(old=>({...old,...patch,mismatch_confirmed:patch.mismatch_confirmed??false}));
 const update=(id:string,patch:Partial<ItemForm>)=>{setItems(old=>old.map(i=>i.id===id?{...i,...patch}:i));setForm(old=>({...old,mismatch_confirmed:false}));};
 const total=maintenanceTotal(items),difference=receiptDifference(total,form.receipt_total),vehicle=data.vehicles.find(v=>v.id===form.vehicle_id);
 const sourceMileage=reliableMaintenanceMileage(data.mileage,form.vehicle_id,form.service_date);
 const suggestions=Array.from(new Set(data.items.map(i=>i.description))).sort();
 const submit=async(e:FormEvent)=>{
  e.preventDefault();if(lock.current||uploadState.busy||!can("business:write"))return;setError(null);
  if(!vehicle||!validMaintenanceDate(form.service_date)||form.service_date>maintenanceToday()||!items.length||items.some(i=>!i.description.trim()||(i.reminder_km!==null&&form.odometer===null&&i.override_km===null)||(i.mode==="date"&&!i.override_date)||(i.mode==="odometer"&&i.override_km===null)||(i.mode==="months"&&!i.reminder_months)||(i.mode==="mileage"&&!i.reminder_km&&i.override_km===null)||(i.mode==="both"&&(!i.reminder_months||!i.reminder_km))||(i.override_date&&i.override_date<form.service_date)||(i.override_km!==null&&form.odometer!==null&&i.override_km<form.odometer))||total>9999999999.99||(form.returned_at&&(!form.off_road_at||form.returned_at<form.off_road_at))){setError("invalid");return;}
  if(difference!==null&&difference!==0&&!form.mismatch_confirmed){setError("invalid");return;}
  lock.current=true;setBusy(true);try{const r=await saveMaintenanceRecord(form,items.map(({mode,...item})=>item),savedRecord?.updated_at??null);setSavedRecord(r);setJustSaved(true);onSaved();window.setTimeout(()=>document.getElementById("maintenance-receipts")?.scrollIntoView({behavior:"smooth",block:"center"}),0);}catch(err){setError(String((err as {message?:string}).message??err).includes("CONFLICT")?"conflict":"saveError");}finally{setBusy(false);lock.current=false;}
 };
 return <section className="surface-card space-y-4 p-4 sm:p-5" id="maintenance-form"><div className="flex flex-wrap justify-between gap-2"><h3 className="section-title">{record?c.edit:c.add}</h3><button className="btn-secondary" disabled={busy||uploadState.busy} onClick={()=>{if(!uploadState.pending||window.confirm(c.closeWithFiles))onClose();}}>{c.close}</button></div><p className="text-sm text-slate-500">{c.formHelp}</p><form onSubmit={submit} className="space-y-4">
 {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-800">{c[error]}</p>}{justSaved&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{c.receiptSaved}</p>}
 <fieldset disabled={busy||uploadState.busy||!can("business:write")} className="space-y-5 disabled:opacity-60"><section className="space-y-3 rounded-2xl border border-violet-100 bg-white p-3 sm:p-4"><h4 className="font-semibold text-violet-950">{c.vehicleReceiptSection}</h4><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
 <Field label={`${c.vehicle} *`}><select required className="form-input" value={form.vehicle_id} onChange={e=>set({vehicle_id:e.target.value})}><option value="">{c.select}</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_reg}</option>)}</select></Field>
 <Field label={`${c.serviceDate} *`}><input className="form-input" type="date" min="1900-01-01" max={maintenanceToday()} required value={form.service_date} onChange={e=>set({service_date:e.target.value})}/></Field>
 <Field label={c.mileage}><input className="form-input" type="number" min="0" max="9999999999.99" step="0.01" value={form.odometer??""} onChange={e=>set({odometer:e.target.value===""?null:Number(e.target.value)})}/></Field>
 <Field label={c.garage}><input className="form-input" maxLength={500} value={form.garage??""} onChange={e=>set({garage:e.target.value||null})}/></Field>
 <Field label={c.receiptReference}><input className="form-input" maxLength={500} value={form.receipt_reference??""} onChange={e=>set({receipt_reference:e.target.value||null})}/></Field>
 <Field label={c.receiptTotal}><input className="form-input" type="number" min="0" max="9999999999.99" step="0.01" value={form.receipt_total??""} onChange={e=>set({receipt_total:e.target.value===""?null:Number(e.target.value)})}/></Field>
 </div><p className="text-xs text-slate-500">{c.mileageHelp}</p>{sourceMileage.value!==null&&<div className="rounded-xl bg-violet-50 p-3 text-xs"><p>{c.latestMileage}: {formatNumber(sourceMileage.value,language)} · {formatDate(sourceMileage.date!,language)}</p><p className="my-1 text-slate-500">{c.mileageSourceHelp}</p><button type="button" className="btn-secondary" onClick={()=>set({odometer:sourceMileage.value})}>{c.useMileage}</button></div>}<p className="text-sm text-slate-500">{c.driver}: {maintenanceDriver(data,form.vehicle_id)||c.unassigned}</p></section>
 <div className="space-y-3"><h4 className="font-semibold text-violet-950">{c.itemsSection} *</h4><p className="text-xs text-slate-500">{c.itemsHelp}</p><p className="text-xs text-slate-500">{c.notesNotCopied}</p><datalist id="maintenance-descriptions">{suggestions.map(s=><option key={s} value={s}/>)}</datalist>
 {items.map((item,index)=>{return <div key={item.id} className="space-y-3 rounded-2xl border border-violet-100 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{c.item} {index+1}</strong><div className="flex flex-wrap gap-2"><button className="min-h-11 rounded-lg px-2 text-xs font-medium text-slate-500 hover:bg-violet-50 hover:text-violet-700" type="button" onClick={()=>{setItems([...items,duplicateMaintenanceItem(item,crypto.randomUUID())]);setForm({...form,mismatch_confirmed:false});}}>{c.duplicateItem}</button><button className="min-h-11 rounded-lg px-2 text-xs text-slate-500 hover:bg-rose-50 hover:text-rose-700" type="button" onClick={()=>{if(window.confirm(c.confirmRemoveItem)){setItems(items.filter(i=>i.id!==item.id));setForm({...form,mismatch_confirmed:false});}}}>{c.removeItem}</button></div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label={`${c.descriptionLabel} *`}><input required className="form-input" maxLength={500} list="maintenance-descriptions" value={item.description} onChange={e=>update(item.id,{description:e.target.value})}/></Field><Field label={c.category}><MaintenanceCategorySelect value={item.category} onChange={category=>update(item.id,{category,requirement_id:null,...(category==="grease"&&item.mode==="none"?{reminder_months:12,mode:"months"}:{})})}/></Field>
 <Field label={c.quantity}><input required className="form-input" type="number" min="0" max="1000000" step="0.01" value={item.quantity} onChange={e=>update(item.id,{quantity:Number(e.target.value)})}/></Field><Field label={c.unitPrice}><input required className="form-input" type="number" min="0" max="100000000" step="0.01" value={item.unit_price} onChange={e=>update(item.id,{unit_price:Number(e.target.value)})}/></Field><div className="self-end rounded-xl bg-white p-3 font-semibold">{c.lineTotal}: {formatCurrency(maintenanceLineTotal(item),language)}</div></div>
 <details className="rounded-xl border border-slate-100 p-3"><summary className="cursor-pointer py-2 text-sm text-slate-600">{c.optionalItemDetails}</summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><Field label={c.originalWording}><input className="form-input" maxLength={500} value={item.description_th??""} onChange={e=>update(item.id,{description_th:e.target.value||null})}/></Field> <Field label={c.itemNotes}><input className="form-input" maxLength={2000} placeholder={c.itemNotesHelp} value={item.notes??""} onChange={e=>update(item.id,{notes:e.target.value||null})}/></Field></div></details>
 <MaintenanceReminderFields item={item} form={form} data={data} onChange={patch=>update(item.id,patch)}/></div>;})}
 <button className="btn-secondary" type="button" onClick={()=>setItems([...items,{...newMaintenanceItem(crypto.randomUUID()),mode:"none"}])}>{c.addItem}</button>
 </div><div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><output className="text-lg font-bold" aria-live="polite">{c.calculatedTotal}: {formatCurrency(total,language)}</output>{difference!==null&&<p className={`mt-2 font-semibold ${difference===0?"text-emerald-700":"text-amber-800"}`}>{difference===0?c.matched:`${c.difference}: ${formatCurrency(difference,language)}`}</p>}{difference!==null&&difference!==0&&<><p className="mt-2 text-sm">{c.mismatchWarning}</p><label className="mt-2 flex items-start gap-2 text-sm"><input className="!h-4 !w-4 shrink-0" type="checkbox" required checked={form.mismatch_confirmed} onChange={e=>set({mismatch_confirmed:e.target.checked})}/>{c.confirmMismatch}</label></>}</div>
 <section id="maintenance-receipts" className="scroll-mt-28 space-y-3"><h4 className="font-semibold text-violet-950">{c.receiptSection}</h4>
 {savedRecord&&<MaintenanceAttachmentList attachments={data.attachments.filter(a=>a.record_id===savedRecord.id)} onChange={onSaved}/>}
 <MaintenanceUploader recordId={savedRecord?.id??null} onUploaded={onSaved} onStateChange={setUploadState}/>
 </section>
 <section className="space-y-3 rounded-2xl border border-slate-200 p-3 sm:p-4"><h4 className="font-semibold text-violet-950">{c.optionalSection}</h4><Field label={c.generalNotes}><textarea className="form-input" rows={3} maxLength={10000} placeholder={c.generalNotesHelp} value={form.notes??""} onChange={e=>set({notes:e.target.value||null})}/></Field>
 <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer py-2 text-sm font-semibold">{c.downtimeOptional}</summary><p className="my-2 text-xs text-slate-500">{c.downtimeHelp}</p>
 <div className="grid gap-3 sm:grid-cols-2"><Field label={c.offRoad}><input className="form-input" type="datetime-local" max={timeInput(new Date().toISOString())} value={timeInput(form.off_road_at)} onChange={e=>set({off_road_at:timeValue(e.target.value)})}/></Field><Field label={c.returned}><input className="form-input" type="datetime-local" min={timeInput(form.off_road_at)||undefined} max={timeInput(new Date().toISOString())} value={timeInput(form.returned_at)} onChange={e=>set({returned_at:timeValue(e.target.value)})}/></Field></div><p className="text-xs text-slate-500">{c.thailandTime}</p></details>
 </section><p className="text-xs text-slate-500">{c.noAutomaticOil}</p><div className="sticky bottom-3 z-10 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-violet-100 bg-white/95 p-3 shadow-lg backdrop-blur"><strong className="text-sm">{c.calculatedTotal}: {formatCurrency(total,language)}</strong><button className="btn-primary min-h-11 w-full sm:w-auto" type="submit" disabled={busy||uploadState.busy}>{busy?t.common.saving:uploadState.busy?c.uploading:c.save}</button></div></fieldset>
 </form>
 </section>;
}
