"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {AlertTriangle,CalendarClock,CheckCircle2,Gauge,Plus,RefreshCw,SlidersHorizontal,WalletCards,Wrench} from "lucide-react";
import {Header} from "@/components/header";
import {MaintenanceAttention} from "@/components/maintenance-attention";
import {MaintenanceField as Field} from "@/components/maintenance-fields";
import {MaintenanceHistory} from "@/components/maintenance-history";
import {MaintenancePeriodPresets} from "@/components/maintenance-period-presets";
import {MaintenanceRecordCollection} from "@/components/maintenance-record-collection";
import {MaintenanceRecordForm} from "@/components/maintenance-record-form";
import {MaintenanceRequirements} from "@/components/maintenance-requirements";
import {useAccountAccess} from "@/lib/use-account-access";
import {useLanguage} from "@/lib/language-provider";
import {fetchMaintenanceData,MaintenanceLoadError} from "@/lib/maintenance-data";
import {maintenanceExportRows} from "@/lib/maintenance-export";
import {buildMaintenanceReminders,filterMaintenanceRecords,maintenanceDriver,maintenanceStatusOrder,maintenanceToday,type MaintenanceFilters} from "@/lib/maintenance";
import {maintenanceDateRange,maintenanceVehicleType} from "@/lib/maintenance-ux";
import {MAINTENANCE_CATEGORIES,type MaintenanceData,type MaintenanceRecord} from "@/lib/maintenance-types";
import {maintenanceCategoryLabels} from "@/lib/maintenance-translations";
import {exportToCsv,exportWorkbookToXlsx} from "@/lib/export";
import {formatCurrency,formatDate} from "@/lib/utils";

const baseFilters=():MaintenanceFilters=>({vehicle:"",driver:"",vehicleType:"",category:"",status:"",garage:"",...maintenanceDateRange("thisYear"),search:""});
export default function MaintenancePage(){
 const {t,language}=useLanguage(),c=t.maintenance,{can}=useAccountAccess();
 const [data,setData]=useState<MaintenanceData|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[today,setToday]=useState(maintenanceToday),[filters,setFilters]=useState<MaintenanceFilters>(baseFilters),[form,setForm]=useState<{key:string;record:MaintenanceRecord|null;vehicleId:string}|null>(null),[history,setHistory]=useState<string|null>(null),[showRequirements,setShowRequirements]=useState(false),[filtersOpen,setFiltersOpen]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{setData(await fetchMaintenanceData());setError(null);}catch(caught){setError(caught instanceof MaintenanceLoadError?`${caught.table} (${caught.status}, ${caught.code})`:"");console.error("Maintenance load failed",caught);}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();const vehicle=new URL(window.location.href).searchParams.get("vehicle");if(vehicle){setHistory(vehicle);setFilters(value=>({...value,vehicle}));}const timer=window.setInterval(()=>setToday(maintenanceToday()),60000);return()=>window.clearInterval(timer);},[load]);
 const reminders=useMemo(()=>data?buildMaintenanceReminders(data,today):[],[data,today]),records=useMemo(()=>data?filterMaintenanceRecords(data,filters,reminders):[],[data,filters,reminders]);
 const change=(patch:Partial<MaintenanceFilters>)=>setFilters(old=>({...old,...patch}));
 const openForm=(record:MaintenanceRecord|null,vehicleId="")=>{setForm({key:crypto.randomUUID(),record,vehicleId});window.setTimeout(()=>document.getElementById("maintenance-form")?.scrollIntoView({behavior:"smooth",block:"start"}),0);};
 const openHistory=(vehicleId:string)=>{if(!vehicleId)return;setHistory(vehicleId);window.setTimeout(()=>document.getElementById("maintenance-history")?.scrollIntoView({behavior:"smooth",block:"start"}),0);};
 const exportRows=data?maintenanceExportRows(data,records,language):null,defaultRange=maintenanceDateRange("thisYear",today);
 const activeFilters=[filters.vehicle,filters.driver,filters.vehicleType,filters.category,filters.status,filters.garage,filters.search].filter(Boolean).length+(filters.start!==defaultRange.start||filters.end!==defaultRange.end?1:0);
 const filteredReminders=reminders.filter(r=>{if(!data)return false;const vehicle=data.vehicles.find(v=>v.id===r.vehicle_id),record=data.records.find(v=>v.id===r.record_id);return(!filters.vehicle||filters.vehicle===r.vehicle_id)&&(!filters.driver||data.drivers.some(d=>d.id===filters.driver&&d.active!==false&&d.assigned_vehicle_id===r.vehicle_id))&&(!filters.vehicleType||vehicle?.vehicle_type===filters.vehicleType)&&(!filters.category||r.category===filters.category)&&(!filters.garage||record?.garage===filters.garage)&&`${vehicle?.vehicle_reg} ${maintenanceDriver(data,r.vehicle_id)} ${record?.garage??""} ${record?.receipt_reference??""} ${r.name}`.toLowerCase().includes(filters.search.toLowerCase());});
 const visibleReminders=filteredReminders.filter(r=>filters.status?r.status===filters.status:r.status!=="ok"||r.mileage_unavailable);
 const dashboard=useMemo(()=>{if(!data)return null;const vehicles=data.vehicles.filter(v=>v.active!==false),month=today.slice(0,7),year=today.slice(0,4),active=data.records.filter(r=>!r.is_deleted);let healthOverdue=0,healthSoon=0,healthOk=0;for(const vehicle of vehicles){const own=reminders.filter(r=>r.vehicle_id===vehicle.id);if(own.some(r=>r.status==="overdue"||r.status==="mileageDue"))healthOverdue++;else if(own.some(r=>r.status==="dueSoon"))healthSoon++;else healthOk++;}const sum=(prefix:string)=>active.filter(r=>r.service_date.startsWith(prefix)).reduce((total,r)=>total+Math.round(Number(r.calculated_total)*100),0)/100;return{overdue:reminders.filter(r=>r.status==="overdue"||r.status==="mileageDue").length,due30:reminders.filter(r=>r.days!==null&&r.days>=0&&r.days<=30).length,due2000:reminders.filter(r=>r.km!==null&&r.km>=0&&r.km<=2000).length,serviced:new Set(active.filter(r=>r.service_date.startsWith(month)).map(r=>r.vehicle_id)).size,month:sum(month),year:sum(year),healthOverdue,healthSoon,healthOk,total:Math.max(1,vehicles.length)};},[data,reminders,today]);
 return <div className="maintenance-shell -m-3 min-h-full space-y-4 p-3 sm:-m-4 sm:p-4 lg:-m-5 lg:p-5"><Header title={c.title} description={c.description}/>
 <section className="maintenance-panel p-3 sm:p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-violet-600">{c.fleetSummary}</p><h3 className="mt-0.5 text-lg font-bold text-slate-950">{c.title}</h3></div><div className="flex flex-wrap gap-2"><button className="btn-secondary min-h-10" disabled={busy} onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>{c.refresh}</button><button className="btn-secondary min-h-10" onClick={()=>setShowRequirements(!showRequirements)}>{c.requirements}</button><Link className="btn-secondary min-h-10" href="/maintenance/analytics">{c.analytics}</Link>{can("business:write")&&<button className="btn-primary min-h-10" disabled={!data||error!==null} onClick={()=>openForm(null,filters.vehicle)}><Plus className="h-4 w-4"/>{c.add}</button>}</div></div>{!can("business:write")&&<p className="mt-2 text-sm text-slate-500">{c.readOnly}</p>}{busy&&<div role="status" className="mt-3 h-10 animate-pulse rounded-xl bg-violet-100/60" aria-label={t.common.loading}/>} {error!==null&&<p role="alert" className="mt-3 rounded-xl bg-amber-50 p-3 text-amber-900">{c.loadError}{error&&<span className="mt-1 block text-xs">{error}</span>}</p>}</section>
 {data&&form&&<MaintenanceRecordForm key={form.key} data={data} record={form.record} vehicleId={form.vehicleId} onClose={()=>setForm(null)} onSaved={()=>void load()}/>} {data&&error===null&&<>{showRequirements&&<MaintenanceRequirements data={data} onSaved={()=>void load()}/>} {dashboard&&<><Kpis c={c} language={language} dashboard={dashboard} onStatus={status=>change({status:filters.status===status?"":status})}/><section className="maintenance-panel p-3 sm:p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><div><h3 className="text-sm font-bold text-slate-900">{c.fleetHealth}</h3><p className="text-xs text-slate-500">{dashboard.healthOk} {c.ok} · {dashboard.healthSoon} {c.dueSoon} · {dashboard.healthOverdue} {c.overdue}</p></div></div><div className="flex h-2 w-full max-w-xs overflow-hidden rounded-full bg-slate-100 sm:w-60"><span className="bg-emerald-500" style={{width:`${dashboard.healthOk/dashboard.total*100}%`}}/><span className="bg-amber-400" style={{width:`${dashboard.healthSoon/dashboard.total*100}%`}}/><span className="bg-rose-500" style={{width:`${dashboard.healthOverdue/dashboard.total*100}%`}}/></div></div></section></>}
 <section className="maintenance-panel space-y-3 p-3 sm:p-4"><div className="grid gap-2 md:grid-cols-[minmax(220px,1.6fr)_minmax(140px,1fr)_minmax(150px,1fr)_auto]"><Field label={c.search}><input className="form-input bg-white/80" type="search" value={filters.search} onChange={e=>change({search:e.target.value})}/></Field><Field label={c.vehicle}><select className="form-input bg-white/80" value={filters.vehicle} onChange={e=>change({vehicle:e.target.value})}><option value="">{c.all}</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_reg}</option>)}</select></Field><Field label={c.driver}><select className="form-input bg-white/80" value={filters.driver} onChange={e=>change({driver:e.target.value})}><option value="">{c.all}</option>{data.drivers.filter(d=>d.active!==false).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><button type="button" className="btn-secondary self-end" aria-expanded={filtersOpen} aria-controls="maintenance-more-filters" onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal className="h-4 w-4"/>{c.moreFilters}{activeFilters?` (${activeFilters})`:""}</button></div><div className="flex flex-wrap items-center justify-between gap-2"><MaintenancePeriodPresets start={filters.start} end={filters.end} onChange={change}/>{activeFilters>0&&<button className="text-sm font-semibold text-violet-700 hover:underline" onClick={()=>setFilters(baseFilters())}>{c.clearFilters}</button>}</div>
 <div id="maintenance-more-filters" className={filtersOpen?"grid gap-2 rounded-2xl border border-violet-100 bg-[#f5f3fc] p-3 sm:grid-cols-2 lg:grid-cols-5":"hidden"}><Field label={c.vehicleType}><select className="form-input bg-white/80" value={filters.vehicleType} onChange={e=>change({vehicleType:e.target.value})}><option value="">{c.all}</option>{Array.from(new Set(data.vehicles.map(v=>v.vehicle_type).filter(Boolean))).map(v=><option key={v} value={v!}>{maintenanceVehicleType(v,t.weeklyMileage.oil.vehicleTypes)}</option>)}</select></Field><Field label={c.category}><select className="form-input bg-white/80" value={filters.category} onChange={e=>change({category:e.target.value})}><option value="">{c.all}</option>{MAINTENANCE_CATEGORIES.map(v=><option key={v} value={v}>{maintenanceCategoryLabels[language][v]}</option>)}</select></Field><Field label={c.status}><select className="form-input bg-white/80" value={filters.status} onChange={e=>change({status:e.target.value})}><option value="">{c.all}</option>{maintenanceStatusOrder.map(v=><option key={v} value={v}>{c[v]}</option>)}</select></Field><Field label={c.garage}><select className="form-input bg-white/80" value={filters.garage} onChange={e=>change({garage:e.target.value})}><option value="">{c.all}</option>{Array.from(new Set(data.records.filter(r=>!r.is_deleted).map(r=>r.garage).filter(Boolean))).map(v=><option key={v} value={v!}>{v}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><Field label={c.start}><input className="form-input bg-white/80" type="date" min="1900-01-01" max={filters.end} value={filters.start} onChange={e=>change({start:e.target.value})}/></Field><Field label={c.end}><input className="form-input bg-white/80" type="date" min={filters.start} max={today} value={filters.end} onChange={e=>change({end:e.target.value})}/></Field></div></div><p className="text-xs text-slate-500">{c.period}: {filters.start==="1900-01-01"?c.allTime:formatDate(filters.start,language)} – {formatDate(filters.end,language)} · {c.remindersToday}: {formatDate(today,language)}</p></section>
 <MaintenanceAttention data={data} reminders={visibleReminders} today={today} filters={filters} onAdd={id=>openForm(null,id)} onHistory={openHistory}/><details className="maintenance-panel p-3"><summary className="cursor-pointer py-1 text-sm font-semibold">{c.statusHelp}</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{maintenanceStatusOrder.map(status=><div key={status}><dt className="font-semibold">{c[status]}</dt><dd className="text-sm text-slate-600">{c[(status+"Help") as "okHelp"|"dueSoonHelp"|"mileageDueHelp"|"overdueHelp"|"noHistoryHelp"]}</dd></div>)}</dl></details>
 <section className="maintenance-history-panel space-y-3 p-3 sm:p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-violet-600">{c.periodSummary}</p><h3 className="section-title">{c.visitDetails} ({records.length})</h3></div><div className="flex flex-wrap gap-2"><button className="btn-secondary min-h-10" disabled={!records.length} onClick={()=>exportToCsv(exportRows!.records,"maintenance-visits")}>{c.exportRecords}</button><button className="btn-secondary min-h-10" disabled={!records.length} onClick={()=>exportToCsv(exportRows!.items,"maintenance-items")}>{c.exportItems}</button><button className="btn-secondary min-h-10" disabled={!records.length} onClick={()=>exportWorkbookToXlsx([{name:c.visits,rows:exportRows!.records},{name:c.items,rows:exportRows!.items}],"maintenance-report")}>{c.exportExcel}</button></div></div><MaintenanceRecordCollection records={records} data={data} onEdit={r=>openForm(r)} onChanged={()=>void load()} reminders={reminders}/></section>
 <section className="maintenance-panel p-3"><Field label={c.openHistory}><select className="form-input bg-white/80" value={history??""} onChange={e=>openHistory(e.target.value)}><option value="">{c.select}</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_reg}</option>)}</select></Field></section>{history&&<MaintenanceHistory key={history} vehicleId={history} data={data} onEdit={r=>openForm(r)} onChanged={()=>void load()}/>}</>}</div>;
}
function Kpis({c,language,dashboard,onStatus}:{c:ReturnType<typeof useLanguage>["t"]["maintenance"];language:"en"|"th";dashboard:{overdue:number;due30:number;due2000:number;serviced:number;month:number;year:number};onStatus:(status:string)=>void}){const items=[{label:c.overdue,value:dashboard.overdue,helper:dashboard.overdue?c.highPriority:c.noOverdue,tone:"rose",Icon:AlertTriangle,action:()=>onStatus("overdue")},{label:c.due30,value:dashboard.due30,helper:c.next30Days,tone:"amber",Icon:CalendarClock,action:()=>onStatus("dueSoon")},{label:c.due2000,value:dashboard.due2000,helper:c.remainingKm,tone:"orange",Icon:Gauge,action:()=>document.getElementById("maintenance-attention")?.scrollIntoView({behavior:"smooth"})},{label:c.servicedThisMonth,value:dashboard.serviced,helper:c.currentMonth,tone:"emerald",Icon:Wrench},{label:c.spendThisMonth,value:formatCurrency(dashboard.month,language),helper:c.currentMonth,tone:"blue",Icon:WalletCards},{label:c.spendYtd,value:formatCurrency(dashboard.year,language),helper:c.yearToDate,tone:"violet",Icon:WalletCards}];const colors:Record<string,string>={rose:"border-rose-200 bg-rose-50/80 text-rose-800",amber:"border-amber-200 bg-amber-50/80 text-amber-800",orange:"border-orange-200 bg-orange-50/80 text-orange-800",emerald:"border-emerald-200 bg-emerald-50/80 text-emerald-800",blue:"border-blue-200 bg-blue-50/80 text-blue-800",violet:"border-violet-200 bg-violet-50/80 text-violet-800"};return <div className="grid grid-cols-2 gap-2.5 lg:grid-cols-3 xl:grid-cols-6">{items.map(({label,value,helper,tone,Icon,action})=>{const content=<><div className="flex items-start justify-between gap-2"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><Icon className="h-4 w-4 opacity-70"/></div><p className="mt-2 break-words text-xl font-bold tracking-tight text-slate-950 sm:text-2xl">{value}</p><p className="mt-1 text-[11px] opacity-80">{helper}</p></>;return action?<button key={label} type="button" onClick={action} className={`rounded-2xl border border-l-4 p-3 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${colors[tone]}`}>{content}</button>:<div key={label} className={`rounded-2xl border border-l-4 p-3 shadow-sm ${colors[tone]}`}>{content}</div>;})}</div>}
