export const managementEn = {
  upcoming: "Upcoming Maintenance", profile: "Vehicle Maintenance Profile", filters: "Filters", activeFilters: "active", priority: "Priority", highPriority: "High", mediumPriority: "Medium", informational: "Informational",
  latestMileage: "Latest reliable odometer", mileageDate: "Last mileage date", recurringRepair: "Recurring repair detected", recurrenceHelp: "3 distinct service dates in 9 months for the same repair; category fallback requires 4. Routine servicing is excluded. Review history before taking action.",
  occurrences: "occurrences in 9 months", repeatCategory: "Related repairs in this category", noRepeats: "No recurring repair pattern detected", costIntelligence: "Maintenance cost intelligence", thisMonthSpend: "Spending this month", thisYearSpend: "Spending this year", averageVisit: "Average cost per visit", maintenance10000Km: "Maintenance THB per 10,000 km", supplierSpend: "Garage / supplier spending", commonItems: "Most common maintenance items", frequentVehicles: "Most frequent maintenance visits", originalWording: "Original receipt wording (Thai)", englishDescription: "English description", notesNotCopied: "Duplicating a line keeps its description and price, but clears notes and original receipt wording. Review each new line.",
  intelligencePeriod: "Rankings use the selected reporting period. Month/year spending uses the current calendar month/year. Repair patterns use the trailing 9 months as of today.", profilePeriod: "Mileage cost uses the complete history period below and is shown only when Weekly Mileage fully covers that period.", requirementFirst: "When both intervals are set, whichever comes first is due. Completion values come from linked maintenance items.", latestService: "Last maintenance date", nextRequirement: "Next maintenance requirement", noDueRequirement: "No outstanding configured requirement", useMileage: "Use Weekly Mileage reading", mileageSourceHelp: "This reading is dated as shown; use it only if it represents the odometer at this service. Historical visits never use a later reading.", recurringTrends: "Repeated repair trends", vehicleCostRanking: "Vehicle spending and usage", enteredTotal: "Entered maintenance total", viewAll: "View all", monthlyRuleHelp: "Recurring time intervals use calendar months. For a one-off date, use the item's specific date reminder.",
  fleetHealth: "Fleet health", fleetUpToDate: "Fleet maintenance is currently up to date", noUrgentReminders: "No overdue maintenance or urgent reminders.", attentionSubtitle: "Items requiring attention based on date and mileage.", due2000: "Due within 2,000 km", servicedThisMonth: "Vehicles serviced this month", spendThisMonth: "Maintenance spend this month", spendYtd: "Maintenance spend YTD", next30Days: "Next 30 days", noOverdue: "No overdue maintenance", moreFilters: "More filters", clearFilters: "Clear filters", filterCount: "filters", maintenanceSummary: "Maintenance summary", receiptCheck: "Receipt check", highCostRepair: "High-cost repair", inferredMileage: "Nearest Weekly Mileage reading", workSummary: "Work summary", noUrgentItems: "No actionable maintenance items right now", previousMonthComparison: "vs previous month", currentMonth: "Current month", yearToDate: "Year to date",
};
export const managementTh: Record<keyof typeof managementEn, string> = {
  upcoming: "งานบำรุงรักษาที่ใกล้ถึงกำหนด", profile: "ข้อมูลบำรุงรักษาประจำรถ", filters: "ตัวกรอง", activeFilters: "ใช้งาน", priority: "ความสำคัญ", highPriority: "สูง", mediumPriority: "ปานกลาง", informational: "เพื่อทราบ",
  latestMileage: "เลขไมล์ล่าสุดที่เชื่อถือได้", mileageDate: "วันที่บันทึกเลขไมล์ล่าสุด", recurringRepair: "พบการซ่อมซ้ำ", recurrenceHelp: "ซ่อมรายการเดียวกันอย่างน้อย 3 วันที่ต่างกันใน 9 เดือน หรือหมวดเดียวกันอย่างน้อย 4 วัน ไม่รวมงานบำรุงรักษาตามปกติ โปรดตรวจสอบประวัติก่อนดำเนินการ",
  occurrences: "ครั้งใน 9 เดือน", repeatCategory: "งานซ่อมที่เกี่ยวข้องในหมวดนี้", noRepeats: "ไม่พบรูปแบบการซ่อมซ้ำ", costIntelligence: "วิเคราะห์ต้นทุนบำรุงรักษา", thisMonthSpend: "ค่าใช้จ่ายเดือนนี้", thisYearSpend: "ค่าใช้จ่ายปีนี้", averageVisit: "ค่าใช้จ่ายเฉลี่ยต่อครั้ง", maintenance10000Km: "ค่าบำรุงรักษา บาทต่อ 10,000 กม.", supplierSpend: "ค่าใช้จ่ายแยกตามอู่ / ผู้จำหน่าย", commonItems: "รายการบำรุงรักษาที่พบบ่อย", frequentVehicles: "รถที่เข้าบำรุงรักษาบ่อยที่สุด", originalWording: "ข้อความต้นฉบับในใบเสร็จ (ไทย)", englishDescription: "รายละเอียดภาษาอังกฤษ", notesNotCopied: "การคัดลอกแถวจะคงรายละเอียดและราคา แต่ไม่คัดลอกหมายเหตุหรือข้อความต้นฉบับ โปรดตรวจสอบแต่ละรายการใหม่",
  intelligencePeriod: "อันดับใช้ช่วงรายงานที่เลือก ยอดเดือนและปีใช้เดือนและปีปัจจุบัน รูปแบบซ่อมซ้ำใช้ข้อมูลย้อนหลัง 9 เดือนถึงวันนี้", profilePeriod: "ต้นทุนต่อกิโลเมตรใช้ช่วงประวัติทั้งหมดด้านล่าง และแสดงเมื่อเลขไมล์รายสัปดาห์ครอบคลุมครบเท่านั้น", requirementFirst: "หากกำหนดทั้งระยะทางและเวลา จะถึงกำหนดเมื่อถึงค่าใดค่าหนึ่งก่อน ข้อมูลการทำล่าสุดมาจากรายการบำรุงรักษาที่เชื่อมโยง", latestService: "วันที่บำรุงรักษาล่าสุด", nextRequirement: "งานบำรุงรักษาถัดไป", noDueRequirement: "ไม่มีงานที่กำหนดไว้ซึ่งต้องติดตาม", useMileage: "ใช้เลขไมล์รายสัปดาห์", mileageSourceHelp: "เลขไมล์นี้เป็นข้อมูล ณ วันที่แสดง ใช้เมื่อสอดคล้องกับเลขไมล์ขณะเข้าบำรุงรักษาเท่านั้น ไม่ใช้เลขไมล์ภายหลังสำหรับประวัติย้อนหลัง", recurringTrends: "แนวโน้มการซ่อมซ้ำ", vehicleCostRanking: "ค่าใช้จ่ายรถและการใช้งาน", enteredTotal: "ยอดรวมบำรุงรักษาที่กรอก", viewAll: "ดูทั้งหมด", monthlyRuleHelp: "รอบเวลาที่ทำซ้ำกำหนดเป็นเดือนปฏิทิน หากต้องการวันเฉพาะครั้งเดียว ให้ใช้การเตือนตามวันที่ในรายการ",
  fleetHealth: "สุขภาพรถทั้งฝูง", fleetUpToDate: "งานบำรุงรักษาของรถทั้งหมดเป็นปัจจุบัน", noUrgentReminders: "ไม่มีงานเกินกำหนดหรือการเตือนเร่งด่วน", attentionSubtitle: "รายการที่ต้องติดตามตามวันที่และเลขไมล์", due2000: "ครบกำหนดภายใน 2,000 กม.", servicedThisMonth: "รถที่เข้าบริการเดือนนี้", spendThisMonth: "ค่าบำรุงรักษาเดือนนี้", spendYtd: "ค่าบำรุงรักษาตั้งแต่ต้นปี", next30Days: "30 วันข้างหน้า", noOverdue: "ไม่มีงานเกินกำหนด", moreFilters: "ตัวกรองเพิ่มเติม", clearFilters: "ล้างตัวกรอง", filterCount: "ตัวกรอง", maintenanceSummary: "สรุปการบำรุงรักษา", receiptCheck: "ตรวจสอบใบเสร็จ", highCostRepair: "งานซ่อมค่าใช้จ่ายสูง", inferredMileage: "เลขไมล์รายสัปดาห์ที่ใกล้วันที่บริการที่สุด", workSummary: "สรุปงาน", noUrgentItems: "ขณะนี้ไม่มีรายการบำรุงรักษาที่ต้องดำเนินการ", previousMonthComparison: "เทียบเดือนก่อน", currentMonth: "เดือนปัจจุบัน", yearToDate: "ตั้งแต่ต้นปี",
};
