"use client";
import { maintenanceVehicleType } from "@/lib/maintenance-ux";
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {MaintenanceCostIntelligence} from "@/components/maintenance-cost-intelligence";
import {MaintenancePeriodPresets} from "@/components/maintenance-period-presets";
import {maintenanceDataIssues,maintenanceFleetSummary} from "@/lib/maintenance-ux";
import {Header} from "@/components/header";
import {MaintenanceField as Field} from "@/components/maintenance-fields";
import {useLanguage} from "@/lib/language-provider";
import {fetchMaintenanceData,MaintenanceLoadError} from "@/lib/maintenance-data";
import {maintenanceAnalytics,maintenanceObservation,maintenanceToday,validMaintenanceDate} from "@/lib/maintenance";
import type {MaintenanceData} from "@/lib/maintenance-types";
import {maintenanceCategoryLabels} from "@/lib/maintenance-translations";
import {formatCurrency,formatDate,formatNumber} from "@/lib/utils";
export default function MaintenanceAnalyticsPage(){
 const {t,language}=useLanguage(),c=t.maintenance;const [data,setData]=useState<MaintenanceData|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(true),[vehicle,setVehicle]=useState(""),[type,setType]=useState(""),[start,setStart]=useState(`${maintenanceToday().slice(0,4)}-01-01`),[end,setEnd]=useState(maintenanceToday()),[event,setEvent]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{setData(await fetchMaintenanceData(true));setError(null);}catch(caught){setData(null);setError(caught instanceof MaintenanceLoadError ? `${caught.table} (${caught.status}, ${caught.code})` : "");console.error("Maintenance load failed",caught);}finally{setBusy(false);}},[]);
 useEffect(()=>{const p=new URL(window.location.href).searchParams;setVehicle(p.get("vehicle")??"");if(validMaintenanceDate(p.get("start")??""))setStart(p.get("start")!);if(validMaintenanceDate(p.get("end")??""))setEnd(p.get("end")!);void load();},[load]);
 const valid=validMaintenanceDate(start)&&validMaintenanceDate(end)&&start<=end;
 const rows=useMemo(()=>data&&valid?data.vehicles.filter(v=>(!vehicle||v.id===vehicle)&&(!type||v.vehicle_type===type)).map(v=>({vehicle:v,...maintenanceAnalytics(data,v.id,start,end)})).sort((a,b)=>(a.vehicle.vehicle_type??"").localeCompare(b.vehicle.vehicle_type??"")||b.total-a.total):[],[data,valid,vehicle,type,start,end]);
 const summary=useMemo(()=>data&&valid?maintenanceFleetSummary(data,rows.map(row=>row.vehicle.id),start,end):null,[data,valid,rows,start,end]);
 const service=data?.records.find(r=>r.id===event),observation=data&&service?maintenanceObservation(data,service):null;
 const metric=(n:number|null,money=false)=>n===null?c.insufficient:money?formatCurrency(n,language):formatNumber(n,language,2);
 return <div className="space-y-4"><Header title={c.analytics} description={c.analyticsDescription}/><section className="surface-card space-y-3 p-4 sm:p-5"><div className="flex flex-wrap justify-between gap-2"><Link className="btn-secondary" href="/vehicle-performance">{t.nav.vehiclePerformance}</Link><Link className="btn-secondary" href="/maintenance">{c.title}</Link><button className="btn-secondary" disabled={busy} onClick={()=>void load()}>{c.refresh}</button></div><p className="text-sm font-semibold">{c.period}: {start==="1900-01-01"?c.allTime:formatDate(start,language)} – {formatDate(end,language)}</p><p className="text-xs text-slate-500">{c.coverageHint}</p>{busy&&<p role="status">{t.common.loading}</p>}{error!==null&&<p role="alert" className="text-amber-800">{c.loadError}{error&&<span className="mt-1 block text-xs">{error}</span>}</p>}{!valid&&<p role="alert">{c.noDates}</p>}
 <MaintenancePeriodPresets start={start} end={end} onChange={range=>{setStart(range.start);setEnd(range.end);setEvent("");}}/>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label={c.start}><input className="form-input" type="date" max={end} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label={c.end}><input className="form-input" type="date" min={start} max={maintenanceToday()} value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label={c.vehicle}><select className="form-input" value={vehicle} onChange={e=>{setVehicle(e.target.value);setEvent("");}}><option value="">{c.all}</option>{data?.vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_reg}</option>)}</select></Field><Field label={c.vehicleType}><select className="form-input" value={type} onChange={e=>setType(e.target.value)}><option value="">{c.all}</option>{Array.from(new Set(data?.vehicles.map(v=>v.vehicle_type).filter(Boolean))).map(v=><option key={v} value={v!}>{maintenanceVehicleType(v,t.weeklyMileage.oil.vehicleTypes)}</option>)}</select></Field></div></section>
 {summary&&error===null&&<section className="surface-card space-y-3 p-4 sm:p-5"><h3 className="section-title">{c.fleetSummary}</h3><p className="text-xs text-slate-500">{c.summaryHelp}</p><div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{[[c.spending,formatCurrency(summary.total,language)],[c.vehiclesServiced,String(summary.serviced)],[c.visits,String(summary.records)],[c.overdueReminders,String(summary.overdue)],[c.due30,String(summary.due30)],[c.highestSpend,summary.highest?`${data?.vehicles.find(v=>v.id===summary.highest!.vehicleId)?.vehicle_reg??"—"} · ${formatCurrency(summary.highest.total,language)}`:"—"]].map(([label,value])=><div key={label} className="rounded-xl bg-violet-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 break-words text-lg font-bold">{value}</p></div>)}</div></section>}
 {data&&valid&&error===null&&<MaintenanceCostIntelligence data={data} vehicleIds={rows.map(r=>r.vehicle.id)} start={start} end={end}/>}
 {error===null&&rows.map(row=><section key={row.vehicle.id} className="surface-card space-y-4 p-4 sm:p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="section-title">{row.vehicle.vehicle_reg} · {maintenanceVehicleType(row.vehicle.vehicle_type,t.weeklyMileage.oil.vehicleTypes)}</h3><Link className="text-sm text-violet-700 underline" href={`/maintenance?vehicle=${row.vehicle.id}`}>{c.history}</Link></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[c.spending,metric(row.total,true)],[c.distance,metric(row.distance)],[c.maintenanceKm,metric(row.maintenancePerKm,true)],[c.fuelKm,metric(row.fuelPerKm,true)],[c.combinedKm,metric(row.combinedPerKm,true)],[c.visits,String(row.visits)],[c.itemCount,String(row.itemCount)],[c.downtime,`${metric(row.downtime)} ${c.hours}`],[c.overdue,String(row.overdue)],[c.upcoming,String(row.upcoming)]].map(([label,value])=><div key={label} className="rounded-xl border border-violet-100 bg-violet-50/40 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-semibold">{value}</p></div>)}</div><p className="text-xs text-slate-500">{c.remindersToday}: {formatDate(maintenanceToday(),language)}</p>{data&&maintenanceDataIssues(data,row.vehicle.id,start,end).length>0&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><p className="font-semibold">{c.dataQuality}</p><ul className="mt-1 list-disc space-y-1 pl-5">{maintenanceDataIssues(data,row.vehicle.id,start,end).map(issue=><li key={issue}>{c[issue]}</li>)}</ul></div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[c.categorySpending,row.byCategory],[c.monthlyTrend,row.monthly],[c.yearlyTrend,row.yearly],[c.repeatItems,row.repeats]].map(([label,values])=><div key={String(label)}><h4 className="mb-2 font-semibold">{String(label)}</h4><div className="space-y-2">{Object.entries(values).sort((a,b)=>label===c.repeatItems?b[1]-a[1]:a[0].localeCompare(b[0])).map(([key,value])=><div key={key} className="flex justify-between gap-2 border-b border-slate-100 pb-1 text-sm"><span className="break-words">{label===c.categorySpending?maintenanceCategoryLabels[language][key as keyof typeof maintenanceCategoryLabels.en]:key}</span><span className="shrink-0">{label===c.repeatItems?value:formatCurrency(Number(value)/100,language)}</span></div>)}</div></div>)}</div></section>)}
 {data&&error===null&&<section className="surface-card space-y-3 p-4 sm:p-5"><h3 className="section-title">{c.observation}</h3><p className="text-sm text-slate-500">{c.observationHint}</p><Field label={c.serviceDate}><select className="form-input" value={event} onChange={e=>setEvent(e.target.value)}><option value="">{c.select}</option>{data.records.filter(r=>!r.is_deleted&&(!vehicle||r.vehicle_id===vehicle)&&r.service_date>=start&&r.service_date<=end).map(r=><option value={r.id} key={r.id}>{data.vehicles.find(v=>v.id===r.vehicle_id)?.vehicle_reg} · {r.service_date}</option>)}</select></Field>{event&&!observation&&<p>{c.insufficient}</p>}{observation&&<div className="grid gap-3 sm:grid-cols-2">{[[c.before,observation.before],[c.after,observation.after]].map(([label,raw])=>{const window=raw as NonNullable<typeof observation>["before"];return <div key={String(label)} className="rounded-xl border p-3"><strong>{String(label)}: {formatNumber(window.kmPerLitre,language,2)} {c.kmL}</strong><p className="text-sm">{window.start} – {window.end}</p><p className="text-xs text-slate-500">{c.coverage}: {window.coverageStart} – {window.coverageEnd} · {window.cycles} {c.cycles}</p></div>;})}</div>}</section>}
 </div>;
}
